### ISSUE TITLE
Remove `updatehistory` from `NativeContractState`

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#1000]
See https://github.com/neo-project/neo-modules/pull/851

Note, this change happened under `v3.6.3`

Don't remove the functionality in neow3j to prevent necessity for a major release. Only depricate the relevant methods.

**Comment by csmuller** [comment]
Deprecated the `getUpdateHistory` method for now.
Real removal will be done in https://github.com/neow3j/neow3j/issues/1007.
