### ISSUE TITLE
Smart Contract deployment

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#101]
Enable neow3j users to deploy smart contracts using neow3j.

- [x] Contract Manifest and ScriptHeader
- [x] Refactor of `ContractDeploy` class and related ones

**Comment by Tommo-L** [comment]
It's recommend to set the contact information about the contract in manifest file, as neo3 have moved those properties, replaced by `Extra` field in manifest file.

**Comment by gsmachado** [comment]
- [ ] Contract Manifest and ScriptHeader
- [ ] Refactor of `ContractDeploy` class and related ones
