### ISSUE TITLE
Add support for setting `neow3jCompile` gradle task as cacheable or non-cacheable

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#1016]
Gradle daemon relies on a powerful caching mechanism (yet, annoying, sometimes).

As a developer, it would be nice if I could set the neow3jCompile task as non-cacheable, for whatever reason. E.g., this would give more confidence to developers who frequently change code (in the smart contract) and would like to make sure that the compilation task is getting the latest and greatest version.

**Comment by Lorenzobattistela** [comment]
Hey @gsmachado , I'm up to picking up this issue. Feel free to assign me. 
I think it is possible to change caching options through gradle API. I'll investigate it further and open a PR

**Comment by gsmachado** [comment]
Cool!

As it was mentioned in Discord:

You might want to start reading some stuff from here:
https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details

The challenge is to do this programmatically, and not using groovy.
I mean, when I say "programmatically", I refer to implement this in the neow3j gradle plugin itself: https://github.com/neow3j/neow3j/tree/main/gradle-plugin

References:
- https://github.com/neow3j/neow3j/blob/main/gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileTask.java
- https://github.com/neow3j/neow3j/blob/main/gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileAction.java
- ...and other files within that directory (within the gradle-plugin module).

**Comment by Lorenzobattistela** [comment]
@gsmachado tbh, I'm not really familiar with gradle, so I'm learning while researching this. I found this: https://docs.gradle.org/current/javadoc/org/gradle/caching/configuration/BuildCacheConfiguration.html
On the java API, but it seems I can only get the local build cache configuration, and not change it. I also understand that we can change it by changing the `.properties` file for gradle (that i assume is the gradle wrapper on neow3j) - https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable

I'm not sure if we can enable / disable this through the java api, my second thoughts on how to approach this is write to this properties file from our plugins. This seems a little odd, since touching a properties file is not ideal. 

What do you think? Maybe I'm going in the wrong direction

**Comment by gsmachado** [comment]
Sure, no worries.

I would go in this direction:

- Add an attribute called `cache` in [this file](https://github.com/neow3j/neow3j/blob/main/gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginExtension.java). You'll also need to add this flag in [this file](https://github.com/neow3j/neow3j/blob/main/gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileTask.java#L18-L31). This will enable to add a flag in the [`neow3jCompile` directive](https://github.com/neow3j/neow3j-boilerplate-contracts/blob/main/build.gradle#L38-L40) of where you're using neow3j gradle-plugin.
- Then, [in this file](https://github.com/neow3j/neow3j/blob/main/gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPlugin.java#L35-L41), I would suggest to try something like this:

```java
task.getOutputs().cacheIf(spec -> cacheFlagSpec());
```

Something like this.

I know that `task.getOutputs()` returns `org.gradle.api.internal.TaskOutputsInternal` class, which extends `TaskOutputs` class. Then, [`TaskOutputs`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html) has a [`.cacheIf()`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html#cacheIf-org.gradle.api.specs.Spec-) method.

What we want first is to enable or disable the cache of outputs. It's not clear yet if we'd need to also disable cache from the `Java` tasks. But this is something we can look into after.

**Comment by gsmachado** [comment]
Actually, I'd say you need to understand how Gradle works with inputs and outputs of tasks, and where the cache functionality can be applied by Gradle daemon. That would make your life a bit easier to play with gradle plugin development. 😄

**Comment by Lorenzobattistela** [comment]
We can close this!
