### ISSUE TITLE
Is there support to Math.Pow? (Or equivalent)

### ISSUE THREAD

**Issue by lock9** [neow3j/neow3j#1028]
In most of our contract examples, we use something like this: `total_supply = 100000 * 10 ** decimals()`

How can we achieve this in Java? I thought this was possible using the `^` operator, but it doesn't work. I've tried Math.random but it doesn't compile. 

Is there an alternative?

**Comment by csmuller** [comment]
It's a bit hidden but you can find a `pow` method on the devpack's Helper class.

https://github.com/neow3j/neow3j/blob/main/devpack%2Fsrc%2Fmain%2Fjava%2Fio%2Fneow3j%2Fdevpack%2FHelper.java

Sorry, i'm on the phone and couldn't link to the method driectly.

**Comment by lock9** [comment]
Great, thank you.
