### ISSUE TITLE
Compiler is not updating the code / manifest

### ISSUE THREAD

**Issue by lock9** [neow3j/neow3j#1029]
**Description of the bug**
I have a smart contract in Java; nothing changes when I update the code and recompile it. I have to manually delete the files to get an updated version of my code.

**To Reproduce**
1. Create/Open a Java smart contract
2. Compile it. Check the manifest.
3. Change the code, like a method name or annotation, and recompile it. Suggestion: Change the display name.
4. Check the manifest.json. It won't have changed.

**Expected behavior**
It should generate new files.

**Platform and Software**
 - OS: macOS 13.2.1 (22D68)
 - Software Version: 3.22.0

Additional context:
I'm getting this output, even when there are changes in code:
```2 actionable tasks: 2 up-to-date```

**Comment by csmuller** [comment]
Hi @lock9, thanks for reporting the issue. We encountered this too since the last neow3j update (https://github.com/neow3j/neow3j/pull/1016). A fix is in progress [here](https://github.com/neow3j/neow3j/issues/1026).

**Comment by lock9** [comment]
Thank you for the update @csmuller . I'll be waiting then. Thanks

**Comment by gsmachado** [comment]
#1026 is merged. We will release a minor version soon.

**Comment by lock9** [comment]
Thanks. I'll test it this week.

**Comment by lock9** [comment]
It worked! Thanks!
