### ISSUE TITLE
[Neo 3.7.0] Update RPC `getversion`

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#1037]
Context: https://github.com/neo-project/neo-modules/commit/da5ad4c1ac4cccebc55775afdeddf78621df9995

- Delete `wsport` (https://github.com/neo-project/neo-modules/pull/859/files)
- Extend `getversion` with new fields (https://github.com/neo-project/neo-modules/pull/878/files)

**Comment by thedanielmark** [comment]
Hi @mialbu,

I have removed `wsport` and all checks seem to have passed. Could you please verify my commit?
