### ISSUE TITLE
Rename `Hash.sha3()` to `Hash.keccak256()`

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#1045]
The submitted SHA-3 Keccak hashing is different from the finalized SHA-3 standard released by NIST due to a different padding. The former (submitted version) is commonly referred to as `keccak256` in the web3 space, e.g., in Neo N3's native contract `CryptoLib`. Neow3j provides a method `Hash.sha3()` that implements that algorithm and **not** the finalized SHA-3 standard by NIST. Thus, neow3j should rename this function to `Hash.keccak256()` to avoid confusion.

**Comment by gsmachado** [comment]
Maybe, @thedanielmark could take this? It's a simple one, but requires some attention for running tests, etc.
