### ISSUE TITLE
JSON-RPC methods for Neo 3

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#106]
As a user, I would like to call new Neo3 JSON-RPC methods. Also, I expect that old Neo2 methods are properly deprecated in the neow3j method API.

- [x] RequestTest and ResponseTest should be "passing"
- [x] Adapt tests on `JsonRpc2_0RxTest.java` -- check if they are correctly working for Neo3

**Comment by mialbu** [comment]
I could not find any example of attributes used or how such is structured. So we should keep this in mind.

**Comment by gsmachado** [comment]
@mialbu Ok... I've come up of what it's still missing for this issue:

- [ ] Implement unit tests for the following: https://github.com/neow3j/neow3j/blob/develop-3.x/core/src/main/java/io/neow3j/protocol/core/Neo.java#L169-L178 . All the methods should be covered by unit tests, mainly the ones with date ranges. If tests are already there, then this task is done.
- [ ] Implement unit tests for https://github.com/neow3j/neow3j/blob/develop-3.x/core/src/main/java/io/neow3j/protocol/core/Neo.java#L90-L91 . Also, if the tests are already there, fine, then this task is done.
- [ ] Check/Update units tests for https://github.com/neow3j/neow3j/blob/develop-3.x/core/src/main/java/io/neow3j/protocol/rx/Neow3jRx.java class. Basically, we need to check if something changed from Neo2 and adapt.

You can create another branch for those.

**Comment by gsmachado** [comment]
In my point of view, this is finally done!

Of course, improvements have to be made, but we did the vast majority of the JSON-RPC work.
