### ISSUE TITLE
Override constants/configs in neow3j

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#107]
As a developer, I would like to specify different values for, e.g., attributes found in the `NeoConstants` class. A good example is that the PrivateNet addresses could use prefix `0x37` (55) instead of `0x17`. I would like to have a way to change that in the default neow3j config.

Default values should be set, and only override if explicitly specified.

**Comment by gsmachado** [comment]
@csmuller could we also close this one? 😄 I think so, right?

**Comment by csmuller** [comment]
Yes, for now our simple solution does the job.
