### ISSUE TITLE
Streamline BinaryReader/BinaryWriter

### ISSUE THREAD

**Issue by ixje** [neow3j/neow3j#1079]
**Summary or problem description**
- BinaryReader and BinaryWriter have no methods to read/write as `uint64`
- BinaryReader can read `int16` but BinaryWriter has no method to write `int16`

Those specific methods might not be in use for consuming NEO specific content, but I think it would be nice to be able to use the same classes to serialize/deserialize other data in a project that already has neow3j as dependency.

**Do you have any solution you want to propose?**
add the missing methods

**What part of neow3j does this apply to?**
- core / serialization

PS: this 34-bit might be a typo 
https://github.com/neow3j/neow3j/blob/dcb642b11577e19ae0d01d025a6868a9e224cfa5/core/src/main/java/io/neow3j/serialization/BinaryReader.java#L179

**Comment by gsmachado** [comment]
Thanks, @ixje 

@OT-kraftchain @mialbu can someone take this issue?
