### ISSUE TITLE
Adapt wallet model to Neo 3

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#112]
Update the account model of neow3j to conform to changes in Neo 3.

At the same time refactor parts of the wallet implementation that could use improvements.

- [x] Create a wallet
- [x] Load a wallet from file or from string or stream, etc (like it was with Neo2)
- [x] Save a wallet to file (like Neo2 style)
- [x] Create and load accounts, etc (like Neo2 style)
- [x] Create and load BIP39 accounts
- [x] WIF experience
- [x] Account balance
- [x] Handling of a wallet's default account

**Comment by gsmachado** [comment]
Related to #121. Both should be solved to enable the wallet functionality.

**Comment by csmuller** [comment]
Requires a discussion on the API design, i.e. if and how we should add the ability to check account balances.

**Comment by gsmachado** [comment]
great stuff! 👍 💯
