### ISSUE TITLE
Support non-fungible tokens (NFT)

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#114]
Enable support to interact with [NEP-11](https://github.com/neo-project/proposals/pull/41) contracts with a Java wrapper. Similar to how neow3j already supports NEP-5 contracts.

Additionally, determine other features that could be useful in context of NFT contract.

**Comment by gsmachado** [comment]
We decided to not implement this for now because NEP-11 is not yet "final".

**Comment by csmuller** [comment]
Check out the links to example contracts and the committed contract [here](https://github.com/neo-project/neo-devpack-dotnet/issues/239)

**Comment by csmuller** [comment]
Done with  #235.
