### ISSUE TITLE
Add NEP-9 support

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#115]
Create a Java class that can generate URI's compatible with [NEP-9](https://github.com/neo-project/proposals/blob/master/nep-9.mediawiki).

**Comment by gsmachado** [comment]
@mialbu can we close this issue? 😄 👍

**Comment by mialbu** [comment]
Yes, I'll close it. I don't know why this wasn't closed automatically when we merged pull request #119 ...
