### ISSUE TITLE
Create neow3j-devpack

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#116]
Create a module called `neow3j-devpack` where can be imported by Gradle, using the minimum amount of dependencies from neow3j project tree.

- [x] Evaluate the work done on [neo-project/neo-devpack-java](https://github.com/neo-project/neo-devpack-java) 
- [x] Define the annotations for a devpack MVP
- [x] Support: Storage

**Comment by csmuller** [comment]
With the commits so far the compiler is able to compile the Hello World contract.
Further work on the compiler is handled in other issues.
