### ISSUE TITLE
Add NeoToken support

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#118]
Create a Java class implementing the interface of NeoToken giving the developer a convenient abstraction for interacting with the Neo token contract.

- [x] Finish class implementation
  - [x] Implement method for `getNextBlockValidators`
  - [x] Implement method for `vote`
- [x] Implement Unit Tests

Description:
https://github.com/neo-ngd/NEO3-Development-Guide/tree/master/en/SmartContract#neotoken

**Comment by mialbu** [comment]
This is done, I'll close this.
