### ISSUE TITLE
Support generic contract invocations

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#120]
Neow3j must allow the developer to create and execute generic contract invocations for any smart contract.

This depends on the Neo 3 transaction model #102.
More specific abstractions, e.g. for the NeoToken (#118), can be added on top of this.

- [x] Adapt to latest changes in OpCodes and InteropCodes.
- [x] Write JavaDoc for the class `SmartContract`. 
- [x] Write JavaDoc for the class `Invocation`.
- [x] Write unit tests for the class `SmartContract`.
- [x] Write unit tests for the class `Invocation`.

Solves #69

**Comment by mialbu** [comment]
This is done, I'll close it.
