### ISSUE TITLE
Add secp256k1 maintaining secp256r1 support

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#121]
Neo added support to the secp256k1, which can be used in a contract by interoperability syscall, but Neo still uses secp256r1 for the wallet.

Actually, Neo has renamed the syscalls of secp256r1.

![image](https://user-images.githubusercontent.com/2124276/81827884-7cf00280-9539-11ea-9dfd-0b96f69570f3.png)

**Comment by gsmachado** [comment]
@csmuller I think this is done, or something is still missing?

**Comment by csmuller** [comment]
Yes it is done. Closing the issue.
