### ISSUE TITLE
Add Nep5Token support

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#123]
Create a Java class implementing the standard interface of a NEP-5 token giving the developer a convenient abstraction to interact with NEP-5 contracts.

~~Allow a token transfer to use tokens of all accounts in a wallet. First the default account's tokens are used and if the transfer amount is higher then other accounts in the wallet are used.~~ This is covered in issue #133.

**Comment by mialbu** [comment]
This is done, so I'll close it.
