### ISSUE TITLE
JavaDoc updates and fixes

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#127]
As a user of neow3j it's very important to have a reasonable JavaDoc documentation, especially explaining the parameters (inputs) and return values (outputs).

Also, descriptions of the method and class level are important.

**Comment by csmuller** [comment]
This is constantly being improved but we are not using this issue to track the improvements. @gsmachado Can we close it?

**Comment by gsmachado** [comment]
@csmuller agreed. I will close this. 👍 😄
