### ISSUE TITLE
Block subscription test malfunction

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#129]
The test testCatchUpToLatestAndSubscribeToNewBlockObservable in JsonRpc2_0RxTest.java malfunctions.

In some runs the test passes but sometimes the test fails with different outputs:
- only the current blocks are fetched but no new ones
- one or two of the expected three 'new' blocks are not fetched
- no blocks are fetched at all

This behaviour should be checked and fixed.

**Comment by gsmachado** [comment]
@mialbu can you take a look into this?

I'm gonna assign you. We can check this together.

**Comment by mialbu** [comment]
This actually works. I'll close it.
