### ISSUE TITLE
Refactor `StackItem` to use Jackson annotations for deserializing subclasses

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#131]
The `StackItem` class currently uses a custom deserializer to deserialize its various subclasses. 
See `TransactionAttribute` as an example on how to do this.

**Comment by mialbu** [comment]
I tried to do this and it works for all `StackItemTypes` except for Maps. For the `StackItemType` Map, a custom Key deserialiser is needed.

Reason for this:
In a Map-StackItem the value is of type `Map<StackItem, StackItem>`, hence the key-value pair are both StackItems. Using Jackson annotations, however, by default the keys of a Map are deserialised as Strings. This leads to an `InvalidDefinitionException` that asks for a `(Map) Key deserialiser`.

**Comment by gsmachado** [comment]
hmm.. interesting observation, @mialbu. Thus, it seems we can't fully switch to Jackson annotations. We should still survive with the flexibility of custom deserializer/serializer, instead of the beauty of annotations...

So, what do you think, @csmuller, should we close this issue, then?

**Comment by csmuller** [comment]
Would it be hard to write a custom deserializer for `MapStackItem` instead of completely reverting back to the deserializer in `StackItem`?

**Comment by csmuller** [comment]
If we don't see much of an improvement for maintainability or extensibility and can't finish the refactoring properly, we should just close the issue and let it be.

**Comment by gsmachado** [comment]
@mialbu can you provide us feedback on this?

**Comment by mialbu** [comment]
This was merged. I'll close it.
