### ISSUE TITLE
Multi-sender token transfer

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#133]
Currently, the `Nep5Token.transfer(...)` method does only take into account the token balance of the a wallet's default account. This should be extended to all accounts in the wallet, so that if the default account cannot cover the desired amount, the other accounts are used to cover it as well.

The `Invocation` class and its `Builder` do not easily allow this behavior at the moment. An `Invocation` conceptually reflects _one_ invocation of a smart contract, but transferring from multiple accounts in the same transaction implies _multiple_ contract invocations. We need to come up with a design that allows both behaviors.

**Comment by mialbu** [comment]
This is done, I'll close it.
