### ISSUE TITLE
Consider removing the Builder from the Account class

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#135]
`Account` allows instantiation only via a set of static creation methods. These methods return a builder that can be further configured with the properties label, isDefault, and isLocked.
The point of those creation methods is to make sure that only correctly configured accounts, i.e., with at least an address, can be created. 

Because these methods are static and return an `Account` or `Account.Builder` instance, it is impossible to extend `Account` and extend these methods. An extending subclass cannot reuse that code.

The properties label, isDefault, and isLocked - currently configurable only on the Builder - could be made available via setters without averse effects on the account state. Then the Builder becomes redundant. Furthermore, the static creation methods can then be converted into normal constructors because they can return an `Account` directly (instead of a `Builder`).

**Comment by mialbu** [comment]
This was merged. I'll close it.
