### ISSUE TITLE
Support bitwise operators

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#164]
The compiler should support all Java bitwise operators that can be mapped to NeoVM code.
Operators: `&, |, ^, ~, <<,   >>, >>>`
Assignment operators: `&=, |=, ^=, <<=, >>=`

**Comment by csmuller** [comment]
The logical right-shift operator `>>>` is not supported by NeoVM. Thus, it will not be supported by the neow3j-compiler.

**Comment by gsmachado** [comment]
@csmuller should we close this issue, then?

**Comment by csmuller** [comment]
> @csmuller should we close this issue, then?

No, all other bitwise operators (e.g. `>>` or `&`) must still be supported.

**Comment by gsmachado** [comment]
Oh, yes. Good. 😄  👍
