### ISSUE TITLE
Finalize smart contract API 

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#172]
The smart contract API needs to be redesigned with consistency. For example, in some contract invocation methods it is not possible to define a sender account while in others it is. We need to agree on one consistent design that allows enough flexibility but should also be intuitive for the developer to use.

Affected classes are:   
- `SmartContract`   
- `Invocation` and `Invocation.Builder`  
- `Nep5Token` 
- `NeoToken`
- `GasToken`
- `PolicyContract`

Also tackle #162 at the same time.

**Comment by csmuller** [comment]
While testing I used the following construct to call the transfer method on a contract.
```
Invocation i = sc.invoke("transfer")
            .withWallet(w)
            .build()
            .sign();
```
I expected that this would work without problems. But the behavior of the `Invocation.Builder` when not specifying any signers nor a sender is to put one signer with a fee-only scope. Of course the `CheckWitness` check in the smart contract failed because the signer scope did not allow for such a check.
This was quite unintuitive. We should either change this automatic behavior or require the developer to always specify a signer. The new automatic behavior would be to add the signer with the called-on-entry scope.

**Comment by mialbu** [comment]
This was done in pr #210. I'll close the issue.
