### ISSUE TITLE
Create documentation and tutorials for neow3j SDK

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#173]
neow3j.io offers documentation for neow3j SDK versions below 3.0.0. With the changes applied for the coming Neo 3 release the documentation has to be rewritten.
- [x] Concepts on Wallets and Accounts need to be rewritten completely because the related classes have been refactored.
- [x] Sections on contract invocations need to be rewritten and extended. This includes general contract invocations and new features like multi-sender token transfers and transaction tracking.
- [x] New classes like `Nep5Token`, `NeoToken` have to be documented.
- [x] The section on smart contract deployment needs to be rewritten.
- [x] Update/extend neow3j java examples.

The above list is not exhaustive.

**Comment by csmuller** [comment]
Im linking to issue #198 here, because it is about the overall structure of the documentation and should be tackled in correlation with this issues.

**Comment by mialbu** [comment]
This has been done. I'll close the issue.
