### ISSUE TITLE
Complete the implementation of all existing StackItem types

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#194]
For the `StackItem` types `Buffer` and `Pointer` the neow3j SDK is lacking the DTO object to read from and write to JSON representation. This is needed, e.g., when receiving stack results from a script invocation.
The missing `StackItem`s need to be added.

- [x] Buffer StackItem Implementation
- [x] Pointer StackItem Implementation

**Comment by mialbu** [comment]
This was merged in pr #220. I'll close this.
