### ISSUE TITLE
Separate the neow3j docs into devpack/compiler and SDK 

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#198]
I propose that we separate the neow3j external documentation into an SDK and a devpack/compiler part.

**Comment by csmuller** [comment]
We don't need to do this for the 3.2.0 release, but until the next release.

**Comment by csmuller** [comment]
I propose to ignore my proposal of separating the docs 😬 Sorry for my fickleness.
In the state the docs are now, it seems fine that the compiler/devpack are together with the rest.
Someone (@gsmachado, @mialbu) can close this issue if they agree.

**Comment by gsmachado** [comment]
@csmuller yes, we talked about this yesterday and we concluded that it's not required. We just need to give more emphasis on the "Smart Contract Development" section within the "Neo3 Guides". That's all.

I will close this issue.
