### ISSUE TITLE
[Suggestion] Add toString() method for  getPeers()

### ISSUE THREAD

**Issue by cloud8little** [neow3j/neow3j#2]
Current there is no override toString method for class NeoGetPeers, it will return an list without clear message on the connected address/port.
suggest to provide this method to make it easy for user to print the message.

**Comment by gsmachado** [comment]
I included the `toString()` for convenience on the `Peers` class.

It will be available on `1.0.7`.

**Comment by gsmachado** [comment]
@cloud8little a fix was released on `1.0.7`.
If you experience that the issue was not yet fixed, please re-open it.

**Comment by cloud8little** [comment]
Verified on 1.0.7, now it will returns string like below: 
Peers{connected=[AddressEntry{address='113.29.236.150', port=20333}, AddressEntry{address='172.255.228.140', port=20333}, AddressEntry{address='54.169.183.160', port=10333}, AddressEntry{address='120.27.19.223', port=20333}, AddressEntry{address='47.99.35.147', port=20333}, AddressEntry{address='188.42.137.4', port=20333}, AddressEntry{address='68.183.239.200', port=10333}, AddressEntry{address='159.138.1.64', port=20333}, AddressEntry{address='121.40.143.87', port=20333}, AddressEntry{address='85.10.255.54', port=20333}, AddressEntry{address='59.87.61.18', port=20333}, AddressEntry{address='120.78.173.192', port=20333}, AddressEntry{address='198.232.109.106', port=20533}, AddressEntry{address='47.105.51.198', port=20333}, AddressEntry{address='37.59.32.210', port=20333}, AddressEntry{address='54.249.61.25', port=20333}, AddressEntry{address='139.99.148.127', port=20333}, AddressEntry{address='95.183.55.59', port=20333}, AddressEntry{address='99.79.9.119', port=20333}, AddressEntry{address='18.222.168.189', port=10333}, AddressEntry{address='14.155.221.33', port=20333}, AddressEntry{address='89.145.165.246', port=10333}], bad=[], unconnected=[]}
