### ISSUE TITLE
Fixes, improvements, refactorings for the SDK

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#211]
This issue is a collection of bugs and improvements found along the way that should be fixed and applied to the neow3j SDK.

- [x] Extend the `NeoToken` class with a `deregisterCandidate()` and `getCommittee()` method. The NeoToken in neo-core has been extended with those methods.
- [x] Extend the `PolicyContract` class with `getMaxBlockSize()`, `getMaxBlockSystemFee()`, `setMaxBlockSize(int size)`, `setMaxBlockSystemFee(int fee)`.

**Comment by gsmachado** [comment]
@mialbu are these methods in the preview3, or they will be added in the next version?

**Comment by mialbu** [comment]
They are in preview3, I'll implement them and add tests.

**Comment by mialbu** [comment]
The methods have been implemented and merged. I'll close this.
