### ISSUE TITLE
Support Callbacks

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#216]
The devpack and compiler should support callbacks, i.e. support creating a callback from a syscall, a method of the calling contract or a method of another contract, and invoking that callback.

**Comment by gsmachado** [comment]
@csmuller could we create a construction similar to subscribe/observable? I don't know the complexity of that, or if that kind of construction is even possible. Just thinking out loud here...

**Comment by csmuller** [comment]
This doesn't fit into milestone 3.6.0 anymore. Moving it out of the milestone.

**Comment by csmuller** [comment]
Has become obsolete because of #370. Postponing the right tasks, saves time 😏
