### ISSUE TITLE
Adapt to changes in neo3-preview4

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#223]
Neo3 testnet will be released at the beginning of November. Until then we should be up to date with neo3-preview4. Though, preview4 will only be released on Oct 19, i.e., this work cannot start immediately.

### SDK

- ~Adapt `getvalidators` RPC to `getnextblockvalidators` (see https://github.com/neo-project/neo-modules/pull/366).~
- ~ValidUntilBlockIncrement has been changed from 2102400 to 5760 (see https://github.com/neo-project/neo/pull/2042).~
- ~Cover the new Oracle native contract with an API in neow3j (similar to the `PolicyContract`)~
- ~Cover the new Designate native contract with an API in neow3j (similar to the `PolicyContract`)~
- ~Adapt the NEP5Token to the new implementation covered in NEP-17 (see and its links https://github.com/neo-project/neo/pull/2024)~

(for issues to those changes, see https://github.com/neow3j/neow3j/issues/223#issuecomment-737292392)

### Compiler

Breaking:
- ~Remove Manifest properties `hasStorage` and `payable` (see https://github.com/neo-project/neo/pull/2060).~

Non-Breaking:
- ~Add a `List<T>` type to the devpack (see https://github.com/neo-project/neo-devpack-dotnet/pull/361).~
- ~Add `@Contract` classes for `Designation` and `Oracle` (see https://github.com/neo-project/neo-devpack-dotnet/pull/372).~
- ~Add an `OnDeployment` annotation that the developer can add on method level and compiles to a `_deploy` method on the smart contract (see https://github.com/neo-project/neo-devpack-dotnet/pull/364 and https://github.com/neo-project/neo-devpack-dotnet/issues/363)~
- ~Add an `OnVerification` annotation that the developer can add on method level and compiles to a `verify` method on the smart contract (see https://github.com/neo-project/neo-devpack-dotnet/pull/364 and https://github.com/neo-project/neo-devpack-dotnet/issues/363)~
- ~Add an ECPoint type to the devpack (https://github.com/neo-project/neo-devpack-dotnet/pull/362/files#diff-d6c9a6e8f7b14263821a1de3af3a76a5d839e9874d5a2fdce8e307d67be2b6fc)~
- ~Introduce `UInt160` and `UInt256` types to the devpack and compiler that make it clearer to the developer with which kind of byte array she is working (https://github.com/neo-project/neo-devpack-dotnet/pull/362/files#diff-e50e2dcbab4e0d6f2f76a11306f5672b0c89e056e0fbf1e09d0a7dae730ab98b).~
- ~Add an oracle class to interface with the oracle native contract (https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Services/Neo/Oracle.cs, native contract at https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Native/Oracle/OracleContract.cs).~
- ~Add support for two new syscalls `Itoa` and  `Atoi` (see https://github.com/neo-project/neo/pull/2043)~

Sources: [Preview4 Checklist](https://github.com/neo-project/neo/issues/1936) and bi-weekly development emails.

**Comment by gsmachado** [comment]
moved to next milestone since neo3-preview4 is not yet released.

**Comment by csmuller** [comment]
Ongoing work. 
Waiting for the preview4 to be released so that we can test against the update neo-node/neo-vm.

**Comment by gsmachado** [comment]
For the SDK part, see the following issues: #280 , #278 , and #263

**Comment by csmuller** [comment]
The tasks concerning the devpack/compiler are now distributed to the issues: #279, #281, #282, #283, #284, #285, #286, #287, and #288.

**Comment by csmuller** [comment]
This issue was replaced by separate issues. Each required change for keeping up with neo3-preview4 lives in it's own issue now. Closing this one.
