### ISSUE TITLE
Failed to load class from SLF4J on startup

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#229]
Every time that neow3j is used/loaded as a library, the user sees the following in the output:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It would be good to hide that or fix that class loading.

- [x] Write about neow3j's usage of slf4j in the external docs.

**Comment by csmuller** [comment]
I'm not sure if we should actually get rid of this error message.
[Here](http://www.slf4j.org/codes.html#StaticLoggerBinder) it says the following:
"Note that embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api."

**Comment by gsmachado** [comment]
@csmuller in this case, I think we should just disable the output of this message, somehow, if this is possible. But not get rid of SLF4J. What do you think?

Because, for example, in our `neow3j-examples-java` repo, all the code that is executed this message shows up. It's confusing IMHO.

**Comment by csmuller** [comment]
In the examples repositories we need to add a LoggerBinder, e.g., logback-classic as a dependecy. then the message should disappear. i can try later today.

**Comment by csmuller** [comment]
I added the dependency to logback to the neo3- and neo2-example projects.

**Comment by gsmachado** [comment]
@csmuller cool!

I'm closing this issue, then.

**Comment by gsmachado** [comment]
@csmuller thinking a bit better, the only thing left to do is: document this somewhere. Or do you think this is not required?

**Comment by csmuller** [comment]
Yes, true. We should document it in the extetnal docs. Let's keep this issue open for that.

**Comment by mialbu** [comment]
I added a section for the logging requirement to the external docs. I'll close the issue.
