### ISSUE TITLE
Configure CI to run integration tests on creation of pull-requests

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#231]
Integration tests in package `core` and `compiler` take much time to run and are therefore excluded form CI builds after git pushes. But for better quality assurance they should be included in pull-request builds.

Investigate what hooks github supports. Can we restrict running integration tests on pull-requests, i.e. commits done to a branch that has an open PR?

**Comment by gsmachado** [comment]
moving to the next milestone due to priority shift.

**Comment by gsmachado** [comment]
see PR #274 for more details! 👍 💯 🎉
