### ISSUE TITLE
wallet module (wrapper)

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#25]
As a developer, I would like to have a different module in `neow3j` that will act as a NEO wallet convenience layer. This module should be called `wallet`, that people can import using maven.

Tasks / Requirements:
 * Create a wallet java module
 * ~~Provide a file-based database layer, to persist information (like a DAO)~~
 * Provide methods to get all past activity related to the wallet (e.g., performed transactions related to NEO, GAS, and other NEP-5 assets, when addresses were added, etc.)

The `wallet` module is intended to connect to one (or more) NEO nodes to perform JSON-RPC calls and get block information relevant for the addresses in the wallet. This information consists for example of UTXOs or transaction outputs for GAS claiming. 
~~The `wallet` module, therefore, requires a file-based database (to be defined) in order to keep the wallets past activities (history).~~  
It relies only on JSON-RPC nodes of version 2.10.2 and higher. It does not depend on other APIs, like the one of a neoscan server.

Features will be specified on different issues and might be referenced.

**Comment by claudemiller** [comment]
As of neo-cli version 2.10.2, there are new JSON-RPC methods that allow the retrieval of claimable GAS and unspent transaction outputs for any address. This removes the need for scanning the blockchain and persisting such information locally in a database. Neow3j will make use of the new RPC methods to retrieve such information. The issue description has been modified accordingly.

**Comment by gsmachado** [comment]
Since other more specialized issues were created (e.g., #70 and #28), and the main part of this issue was already implemented, I'm closing it.
