### ISSUE TITLE
Reference implementation of NEP-11 in Java

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#253]
Create a NFT reference implementation using the neow3j devpack and compiler.
Push the finalization of [NEP-11](https://github.com/neo-project/proposals/pull/41)

Linked to #114.

**Comment by csmuller** [comment]
TODO:
- [ ] The name method can be removed because according to NEP-17 the token name is now in the manifest only.
- [ ] Handling of the token properties.
- [ ] Peer review.

**Comment by gsmachado** [comment]
@mialbu what's the state of this one?

Is this in the https://github.com/neow3j/neow3j-examples-java repo?

**Comment by mialbu** [comment]
Yes, it's in the examples, but still on the develop branch. See [here](https://github.com/neow3j/neow3j-examples-java/blob/develop/neo-n3-examples/src/main/java/io/neow3j/examples/contractdevelopment/contracts/NonFungibleToken.java).

**Comment by mialbu** [comment]
The NEP-11 reference implementation is merged and can be found [here](https://github.com/neow3j/neow3j-examples-java/blob/06a238f37361611bd752393a1fb0110177ec230b/neo-n3-examples/src/main/java/io/neow3j/examples/contractdevelopment/contracts/NonFungibleToken.java).
