### ISSUE TITLE
Missing check for valid BigDecimal value in transfer method

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#257]
When trying to transfer an amount lower than 1 NEO using the `transfer` method of the `Nep5Token`, the exception message `Cannot build a transaction without a script.` is thrown. There should be another exception that is thrown if the provided amount has more decimals than the token that is used. Such a check should be added at the beginning of all `transfer` methods.

Since the amount is computed to a BigInteger (to fractions), the residual decimals of that amount are cut in the computation. So, for NEO that means, when trying to transfer less than 1 Neo, in the code it computes to zero and hence no script is created and a `TransactionBuilder` is returned without a script.

**Comment by gsmachado** [comment]
The [NEO Whitepaper](https://docs.neo.org/docs/en-us/basic/whitepaper.html) says:

> The minimum unit of NEO is 1 and tokens cannot be subdivided.

So, I understand that we still need to have "another exception that is thrown if the provided amount has more decimals than the token that is used", as you mentioned.

However, shouldn't the `NeoToken` class implement that, while the `Nep5Token` is more a generic class that can be extended from?
Or, if you think that `Nep5Token` should implement that, should we fetch the decimals from the contract address and then add an if-statement when a `transfer()` is invoked?

**Comment by mialbu** [comment]
> So, I understand that we still need to have "another exception that is thrown if the provided amount has more decimals than the token that is used", as you mentioned.

Exactly.

> However, shouldn't the `NeoToken` class implement that, while the `Nep5Token` is more a generic class that can be extended from?

In fact, only the `Nep5Token` class is affected by this issue. The `transfer` methods are all implemented there according to the NEP-5 standard, so we need to add a check there and throw an exception, if necessary.

> Or, if you think that `Nep5Token` should implement that, should we fetch the decimals from the contract address and then add an if-statement when a `transfer()` is invoked?

Actually, we are already fetching the decimals from the contract address to compute the correct fraction for the transfer. Of course no contract call is necessary for Neo and Gas, since we have that hardcoded.

**Comment by gsmachado** [comment]
@mialbu ah, ok, it's clear now! Indeed we just need one more check on the `Nep5Token`.
