### ISSUE TITLE
Adapt NEP-5 to the new NEP-17

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#263]
The [NEP-5](https://github.com/neo-project/proposals/blob/master/obsolete/nep-5.mediawiki) token standard was recently replaced by the [NEP-17](https://github.com/neo-project/proposals/pull/126) standard. We need to adapt the changes that affect neow3j and change the naming of NEP-5 related parts to NEP-17.

Check: https://github.com/neo-project/neo/pull/2024

**Comment by mialbu** [comment]
Currently, the transfer parameter data is set to null per default. The support for any data objects will be covered in issue #336.

**Comment by gsmachado** [comment]
PR merged.
