### ISSUE TITLE
Smart contracts return stack items of  type `Integer` when it should be `Boolean`

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#272]
Boolean variables are converted to `PUSH0` or `PUSH1` statements by the neow3j compiler. But using `PUSH` opcodes creates `Integer` instead of `Boolean` stack items on the neo-vm. Therefore, when returning a boolean the stack item returned is of type `Integer`. 

The same problem is present in the neon compiler and is addressed in this [pull-request](https://github.com/neo-project/neo-devpack-dotnet/pull/350). The proposed solution is to convert the stack item to `Boolean` before returning.

So far the converting the stack item before returning it is the only option available to fix this. But the `CONVERT` opcode is relatively expensive and it is questionable if the increased GAS price is worth the consistency gains in the return type.

**Comment by csmuller** [comment]
This needs a discussion with other devs. Is it worth adding a `CONVERT` when the stack item should actually be a `Boolean` instead of `Integer`? This increases the execution cost but makes sure that the return type is coherent with the contract manifest.

**Comment by gsmachado** [comment]
@csmuller 
I think we should introduce some kind of "compiler options" to neow3j. Some compilers out there, like gcc, provide options that can be set when compiling.

I completely agree with your comment here: https://github.com/neo-project/neo-devpack-dotnet/pull/350#issuecomment-694711560 . I think we should enable, by default, the most comprehensible, consistent, and reliable way to provide outputs to developers.

What do you think?

**Comment by csmuller** [comment]
New issue opened for compiler options in #323.

**Comment by csmuller** [comment]
This issue is not necessary anymore due to the improvements made in #445.
