### ISSUE TITLE
Include global variables in debugging information

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#277]
The neow3j compiler adds variables in methods to the debugging information such that their value can be inspected while debugging. This is not the case with global variables, i.e., static class variables. These variables should also be added to the debugging information.

**Comment by csmuller** [comment]
I don't see a way of supporting this with the current version of the debugger. Clarification is pending with Harry.

**Comment by gsmachado** [comment]
@csmuller: did @devhawk get back to you on this?

**Comment by devhawk** [comment]
https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md#v12-format-draft

**Comment by csmuller** [comment]
Solved in #598
