### ISSUE TITLE
Support the special "deploy" contract method

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#283]
- [x] Add an `@OnDeployment` annotation to the devpack that the developer can use for the special `_deploy` method.
- [x] With preview5 the `_deploy` method takes an `Object data` and a `boolean update` parameter. Adapt the current implementation to enforce this.

**Comment by csmuller** [comment]
Partially solved in #309 but the integration tests are waiting for a fix in the test containers. Waiting till the testcointainer is update to a more recent version of the neo-node.

**Comment by gsmachado** [comment]
@csmuller you can test this with `ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:master-latest`, at the moment.

Also, you can check where exactly the `:master-latest` points with the `feature/master-latest`, here: https://github.com/AxLabs/neo3-privatenet-docker/tree/feature/master-latest

**Comment by csmuller** [comment]
Will be fixed by PR #403.

**Comment by csmuller** [comment]
Solved in #403.
