### ISSUE TITLE
Add support for two new syscalls `Itoa` and `Atoi` 

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#287]
The syscalls `Itoa` and `Atoi` have been newly added and convert integers and strings. We need to add them to our Syscall enum and optionally provide devpack helper methods. These methods are helpful, for example, when producing logs with a string and integers.

See neo-project/neo#2043.

**Comment by csmuller** [comment]
I implemented the new syscalls and devpack methods in this branch: https://github.com/neow3j/neow3j/tree/feature/syscalls-itoa-atoi.
The tests currently fail because the privatenet docker image used for the integration tests isn't up to date with neo3-preview4. There are `TODO`s in the affected tests.

**Comment by gsmachado** [comment]
PR merged.
