### ISSUE TITLE
Adapt `NEO` and `GAS` to changes from NEP-5 to NEP-17

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#298]
The classes `NEO` and `GAS` in devpack have the `name` attribute which got removed from NEP-5 to NEP-17.
Remove it from those classes.

**Comment by csmuller** [comment]
Can't be fully tested yet because the tests rely on the privatenet to be up to date with preview4.

Changes are on the branch https://github.com/neow3j/neow3j/tree/feature/devpack-contract-classes.

**Comment by gsmachado** [comment]
@csmuller @mialbu is this already adapted? I think so.

**Comment by gsmachado** [comment]
ok, closing now. PR merged.
