### ISSUE TITLE
Adapt and extend methods of the devpack's Policy contract

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#299]
With neo3-preview4 the `Policy` native contract has modified methods. We need to adapt the `Policy` contract class in the devpack accordingly.

**Comment by csmuller** [comment]
Can't be fully tested yet because the tests rely on the privatenet to be up to date with preview4.

Changes are on the branch https://github.com/neow3j/neow3j/tree/feature/devpack-contract-classes.

**Comment by gsmachado** [comment]
@csmuller I believe that this issue can be closed now. If not, please re-open.
