### ISSUE TITLE
Maven project with "Failure to find io.reactivex.rxjava2:rxandroid:jar:2.1.0" error

### ISSUE THREAD

**Issue by chenquanyu** [neow3j/neow3j#30]
I'm working on a Maven Spring Boot project which needs to add dependency of neow3j.
It reports "Failure to find io.reactivex.rxjava2:rxandroid:jar:2.1.0" error when compiling.
This is an Andriod package so how about supplying 2 kinds of pachages, like web3j:
![image](https://user-images.githubusercontent.com/4393234/57831164-eb936680-77e6-11e9-8f89-5498a22b230d.png)

**Comment by gsmachado** [comment]
Hello @chenquanyu,
can you please paste your `pom.xml` file here as a code snippet? I can't reproduce such issue, since we already add the `io.reactivex.rxjava2:rxandroid` dependency.

**Comment by chenquanyu** [comment]
The  content in pom.xml is as below:

<dependency>
            <groupId>io.neow3j</groupId>
            <artifactId>core</artifactId>
            <version>1.0.10</version>
        </dependency>
And I got an error about reference(Failed to execute goal on project provider-neo: Could not resolve dependencies for project network.arkane:provider-neo:jar:0.5.0-SNAPSHOT: Failure to find io.reactivex.rxjava2:rxandroid:jar:2.1.0 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are force ):

![image](https://user-images.githubusercontent.com/4393234/58018197-bfece500-7b34-11e9-87fa-5465a81e2f0d.png)

**Comment by gsmachado** [comment]
Is this an Android app or a normal Java backend application?

**Comment by chenquanyu** [comment]
normal Java backend application

**Comment by chenquanyu** [comment]
Hi Guil, 
1.0.8 and 1.0.9 have the same issue. It is said that maven only support jar packages and this package has an aar package:
![image](https://user-images.githubusercontent.com/4393234/58065315-db4d0400-7bb7-11e9-84bb-1cb9114a24d6.png)

**Comment by gsmachado** [comment]
Version [1.0.11](https://github.com/neow3j/neow3j/releases/tag/1.0.11) is released.
Please, check if that solves your problem. If not, please, comment here and re-open the issue. Thanks!
