### ISSUE TITLE
Static constructor with local variable leads to exception

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#311]
The neow3j compiler allows the usage of static constructors, but a `NullPointerException` occurs when using local variables in the static constructor. An example contract is shown in the code example below.

```
public class ExampleContract {

    private static int integer;

    static {
        int i = 10;
        integer = i * 2;
    }

    public static int main() throws Exception {
        return integer;
    }
}
```
We assume that the problem only arises because the neo-vm doesn't allow local variables in the INITSSLOT method. That opcode does not allow the definition of local variables.
The solution is to either
(1) build a parser that parses the static constructor at compile time and resolves values of static class variables already at compile time, or 
(2) we simply disallow the usage of local variables in static constructors and throw a compiler exception if the developer uses them.

**Comment by gsmachado** [comment]
@csmuller I think we can close this one, right? 👍
