### ISSUE TITLE
Adapt to adjustable opcode pricing

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#312]
With neo3-preview4 opcodes are not statically priced anymore. Rather, they receive a factor which is multiplied by a base execution fee resulting in the opcode price - the reference opcode for the base fee is NOP.
We need to adapt the neow3j SDK to reflect those changes. This mostly affects the fee calculations for transactions.  
Check out the method  `Wallet.CalculateNetworkFee(...)` in the neo-core (i.e., neo-project/neo). There's the code that calculates the network fee.

See:
- https://github.com/neo-project/neo/issues/1875
- https://github.com/neo-project/neo/pull/2045.

**Comment by gsmachado** [comment]
PR merged.

@csmuller If something is not done in the context of this issue, please re-open.
