### ISSUE TITLE
Remove 'savemethods' from ContractManifest and add a '@Safe' annotation as a replacement

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#314]
The `safemethods` attribute was removed from the contract manifest and moved into the method declaration in the ABI.
- Adapt the `ContractManifest` class and all affected code locations to reflect this change. 
- Implement a new devpack annotation that can be used on smart contract methods to signal that they are safe. 
- Adapt the compiler to support this annotation, such that it adds the information to the ABI.

**Comment by gsmachado** [comment]
@csmuller @mialbu can someone clarify what's the state of this issue? What's missing?

I will assign to milestone 3.7.0.

**Comment by csmuller** [comment]
> @csmuller @mialbu can someone clarify what's the state of this issue? What's missing?

The `@Safe` annotation in the devpack is missing but it doesn't break the release, so it is fine if we move it to 3.7.0.
