### ISSUE TITLE
JSON-RPC: getnep5balances method

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#32]
As a developer, I would like to use the `getnep5balances` JSON-PRC call to easily fetch NEP-5 balances of a specific address.

https://docs.neo.org/en-us/node/cli/latest-version/api/getnep5balances.html

**Comment by gsmachado** [comment]
Still missing integration tests.

**Comment by claudemiller** [comment]
Integration test covered by issue #94
