### ISSUE TITLE
Add output directory config option to Gradle plugin

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#327]
The user should be able to define the output directory for the artifacts produced in contract compilation.
Add a compilation option `outDir` to the `neow3jCompile` Gradle task.

**Comment by gsmachado** [comment]
@csmuller my idea is:

Add `outputDir` as an option option to the `neow3jCompiler{ }` clause in Gradle. E.g.:

```
neow3jCompiler {
    className = "io.neow3j.examples.SmartContractExample"
    debug = true
    outputDir = "/tmp/smart-contract"
}
```

- If the `outputDir` is not present, use the default one (which is how currently it's implemented)
- If the `outputDir` is present, but the path directory does not exist, generate an exception
- If the `outputDir` is present and it exists, use to output the files to it

Let me know if you think that's reasonable.

**Comment by csmuller** [comment]
I think that's the right way to do it 👍
