### ISSUE TITLE
Add exception key to invocation result

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#330]
In the preview4, the invocation result contains a new key `exception` for information of a faulty state of an invocation. This should be added to the `InvocationResult` dto.

**Comment by gsmachado** [comment]
@mialbu is this done? If yes, please, close the issue (move to "Done").

**Comment by gsmachado** [comment]
hmmmm... looking to the #307 PR, I believe this issue is done.

@mialbu please re-open if there's something missing.
