### ISSUE TITLE
Support ContractParameters of type ANY

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#335]
The `ContractParameter` class does not yet support de/serialization of parameters of type ANY. Similarly, the `ScriptBuilder` is missing support for this parameter type.
The ANY parameter type is used, for example, in the new `data` parameter of NEP-17's `transfer` method.

We need to define a way on how we will serialize Java objects. Either we take all the object's field variables and index them in an array or we project them into a map, similar to a JSON serialization.

**Comment by csmuller** [comment]
@gsmachado, @mialbu My current opinion is that the `ANY` parameter type is not instantiated but only used e.g. if any of the other types are allowed. So if a contract method takes `ANY` parameter, it does not mean that we instantiate a parameter with type `ANY` but we can provide any of the other parameter types.

Therefore, I no longer think that we have to support this parameter type as this issue wants it.

**Comment by gsmachado** [comment]
> @gsmachado, @mialbu My current opinion is that the `ANY` parameter type is not instantiated but only used e.g. if any of the other types are allowed. So if a contract method takes `ANY` parameter, it does not mean that we instantiate a parameter with type `ANY` but we can provide any of the other parameter types.

This is something I also observed recently while invoking the `ManagementContract.getContract()` method, and specifying the `Neo` contract. What it returns is the NEF, the manifest, etc. And, in the manifest, when there's something not specified (like, the `permissions` or `trusts` attributes), the `ANY` type was specified... but without "any" value in the `StackItem`. So... the use of `ANY`, in my opinion, has a lot to do when `*` is set in, e.g., [here](https://github.com/neo-project/proposals/pull/114/files#diff-08b779ec43603340fbee5d7e912311f9ca69ebe005a83482a1b0eabb64590da2R81), [here](https://github.com/neo-project/proposals/pull/114/files#diff-08b779ec43603340fbee5d7e912311f9ca69ebe005a83482a1b0eabb64590da2R80), and [here](https://github.com/neo-project/proposals/pull/114/files#diff-08b779ec43603340fbee5d7e912311f9ca69ebe005a83482a1b0eabb64590da2R55), amongst other places (which I still don't know).

> Therefore, I no longer think that we have to support this parameter type as this issue wants it.

Absolutely. Does everyone agree? @mialbu ?

**Comment by mialbu** [comment]
> Absolutely. Does everyone agree? @mialbu ?

Yes, I agree.

**Comment by gsmachado** [comment]
@csmuller and @mialbu: just for your information, I created the label `abandoned`. You can read what `abandoned` means [here](https://github.com/neow3j/neow3j/labels).
