### ISSUE TITLE
Set contract's name when building the manifest

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#338]
In the `ManifestBuilder` the contract's name is not yet set correctly.
Take the contract class name or a name set via the `@DisplayName` for the name attribute in the manifest.

Additionally, change the gradle-plugin such that the name set in the manifest is used as the filename in the NEF, manifest and debuginfo files that are written to disk by the plugin.

**Comment by gsmachado** [comment]
#355 merged.
