### ISSUE TITLE
Check and fix uniformity of token amount handling

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#349]
I don't have the full overview over how we handle token amounts in method parameters and return values, but I think at the moment it is not uniform throughout our library. Sometimes we deal with integers and sometimes with decimals. We should try apply a standard way of handling tokens amounts.

I propose using Strings for method parameters. Strings make sure that developers don't instantiate BigDecimals with floats/doubles, which can lead to a minimally deviating amount than what the dev intended.

**Comment by gsmachado** [comment]
This issue is without any milestone. Should we add this somewhere? Or let's leave it open and prioritize on the go?

**Comment by mialbu** [comment]
This issue was duplicated in #505. I'll mark this one as duplicate, since #505 is already on the project kanban board.
