### ISSUE TITLE
JSON-RPC: getunspents method

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#36]
As a developer, I would like to use the getunspents JSON-PRC call to easily fetch unspent amounts and transaction identifiers for a specific NEO address.

https://docs.neo.org/en-us/node/cli/latest-version/api/getunspents.html

**Comment by claudemiller** [comment]
Only Integration tests missing.

**Comment by claudemiller** [comment]
Integration tests covered by issue #94
