### ISSUE TITLE
Test fetching of the network fee for transactions that have a contracts as signers

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#360]
At the example of a token transfer transaction: If a transfer transaction has a contract as the source of the transfer the contract needs to be a signer of the transaction and the transaction will trigger the contract in verification mode. We need to make sure that in such cases the network fee is correctly returned by the `calculatenetworkfee` RPC method.

**Comment by csmuller** [comment]
In order for this to work, the changes from #430 are required. Only than is it possible to attach the contract itself as a signer to the transaction.
Use the `TransferFromContract` class in the neow3j-examples to test the process.

**Comment by gsmachado** [comment]
#430 was already merged. So, it means that in the next release we would support this, right? 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by csmuller** [comment]
My tests were not successful. This needs more investigation. I think something is not right in our SDK. Opened an issue #565. Will close this one.
