### ISSUE TITLE
Add an OnPayment annotation

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#363]
Any contract can receive payments from NEP-17 token contracts. When this happens the NEP-17 contract will call the `onPayment` method on the receiving contract. Therefore, this is a special method and should receive special treatment, e.g., to ensure the right signature. Add an `OnPayment` annotation to the devpack to support this.

**Comment by gsmachado** [comment]
Just on a side note: I don't know how we would do this, but some standards would need `onXXXPayment()` method as you can [see here](https://github.com/neo-project/proposals/pull/130/files#diff-a19eb8b2eeb4717477086ac65b476fa6d65c50de6a433389378d64b3aa2eea91R355-R380).

Then, should we

1. simply create `@OnPayment` annotations for each supported standard?
2. or, maybe, should we create a `@OnPayment("NEP-X")` which would be converted to `onNEPXPayment()` method if the annotation value (string) is not null (after eliminating `-` or other chars)?
3. or, maybe, should we support option (1) and (2), where if you specify `@OnPayment` it will be translated to `onPayment()`, but if you add `@OnPayment("NEP-11")` it will be translated to `onNEP11Payment()`? 😄 

🚀  🤔

**Comment by csmuller** [comment]
@gsmachado Good point!

I'm in favor of creating `@OnNEPXPayment` annotation for each NEP that defines such a method.
I don't see the advantage of using the `@OnPayment("NEP-X") version because it implies the same amount of work need when a new NEP with an `onPayment` method is added.

**Comment by csmuller** [comment]
Solved in #424.
