### ISSUE TITLE
Network magic number configuration simplification

### ISSUE THREAD

**Issue by roman-khimov** [neow3j/neow3j#373]
One thing I've noticed today is that you're configuring magic number for `NeoConfig` manually (like `NeoConfig.setMagicNumber(new byte[]{0x01, 0x03, 0x00, 0x0})`) while after neo-project/neo-modules#363 (and it's included in preview4) it's possible to get magic number via RPC which can simplify things a bit when you use RPC client already (and it looks like `NeoGetVersion` class needs to be updated also).

**Comment by csmuller** [comment]
Cool, thanks alot for the input Roman! We'll look into it.

**Comment by csmuller** [comment]
Solved in #426.
