### ISSUE TITLE
getContractState by name of native contracts

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#375]
`getcontractstate` now allows fetching the contract state of native contracts by name (additionally to contract hash).
Neow3j's `getContractState` method already takes a string as an argument.

I think we should add an overload method that takes a `ScriptHash` and use the already existing method to cover the new use case, i.e., simply change the method documentation and the parameter name.

**Comment by gsmachado** [comment]
I could take this issue. However, we need to merge #397 PR and fix integration tests first.
