### ISSUE TITLE
invokeContractVerify requires open wallet containing signers 

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#376]
The `invokecontractverify` RPC method requires that the signers added to the call are available in the open wallet on the neo-node.
- [x] Adapt Javadoc of the `Neow3j.invokeContractVerify(...)` method.
- [x] Adapt integration tests in `VerificationMethodIntegrationTest` which should be failing because the wallet is not opened explicitely.

**Comment by gsmachado** [comment]
PR #406 merged. 😄
