### ISSUE TITLE
Update NFToken

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#383]
Neo added a NonFungibleToken class that implements the NFT standard.

- [x] Rename to `NFToken` to `NonFungibleToken`
- [x] Make sure that neow3j's NFT implementation is still up to date with Neo. Adapt it if needed.
- [x] Consider adding a `TokenState` generics class similar to what is done in `NonFungibleToken` in neo-core.

**Comment by gsmachado** [comment]
@mialbu can you update the tasks of this issue? If all are done, please close it. 👍  😄

**Comment by mialbu** [comment]
This was done in pr #407.
