### ISSUE TITLE
Adapt getContractState RPC method

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#385]
The response of the `getcontractstate` RPC method has changed.

- [x] Adapt the `NeoGetContractState` response object (now contains the contract NEF file).

**Comment by gsmachado** [comment]
Partially done.

What it's still missing:

- [ ] Adapt the `ContractManagement.getContract()` method with the serialization of the manifest and nef.

**Comment by gsmachado** [comment]
Due to #470, I think I can set this issue to done. Then I can take #470.

What do you think @csmuller ?

**Comment by csmuller** [comment]
Work is continued in issue #470. Thus, closing this one.
