### ISSUE TITLE
Add the LedgerContract to the devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#390]
In preview5, Neo has moved a lot of block and transaction related functionality to the new `LedgerContract`. The neow3j devpack needs to provide access to this contract for contract developers.

- [ ] Add the `LedgerContract` as a contract interface
- [ ] Adapt other parts of the devpack which have been changed because of the introduction of the ledger contract.

**Comment by gsmachado** [comment]
@csmuller is this done with PR #417 , right?

I'll go ahead and close the issue. 💪  If something's still missing, please re-open.
