### ISSUE TITLE
VM State Enum

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#405]
Neow3j should support the vm states `NONE`, `HALT`, `FAULT` and `BREAK` in an enum.

**Comment by gsmachado** [comment]
@mialbu @csmuller 

Actually, how would we deal with multiple VM states as a result?

![image](https://user-images.githubusercontent.com/2124276/113515662-1bcc8580-9576-11eb-9a97-99c02507aa95.png)

This case can happen, indeed. (at least some time ago)

**Comment by gsmachado** [comment]
for example, should the `state` attribute be a `List<NeoVMStateType>` where the `NeoVMStateType` is an enum?

**Comment by csmuller** [comment]
> This case can happen, indeed. (at least some time ago)

I see no evidence that this still is (or was) something that could happen. According to what I have seen in the neo-vm and neo-modules code, the state will always have a single value.

**Comment by mialbu** [comment]
This was implemented in pr #498.
