### ISSUE TITLE
Rename Nep17Token class to FungibleToken

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#408]
In the neo core, the Nep17 token class was renamed to FungibleToken. Neow3j should adapt this too, it makes the general token naming more coherent.

**Comment by gsmachado** [comment]
Yes, I agree with this one.

The NEP-17 standard will show up in the "SupportedStandards" in the manifest, anyway.

However, we need to add some documentation, explicitly saying that NEP-17 is a FungibleToken... that developers get aware of it, in our examples.

**Comment by gsmachado** [comment]
@mialbu I assume that everything related to this task is also done. Or am I wrong?

If so, can you please close this issue as well?

**Comment by mialbu** [comment]
This was done in pr #407.
