### ISSUE TITLE
Restrict usable values in the SupportedStandards annotation

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#409]
Currently the annotation `SupportedStandards` takes any string as a valid input. Only actual standards should be accepted in this annotation. This also creates consistency in that standards are written with a dash and with capital letters (as it is currently done in the native contracts).

**Comment by gsmachado** [comment]
Do you propose to create specific annotations for each standard?

Maybe we should have both: specific annotations to make it easier for developers, and a flexible annotation that developers can set any `String`.

What do you think?

**Comment by mialbu** [comment]
This depends whether standards other than the standards in the neo-project should be accepted. If only those should be accepted, then setting any `String` in this annotation should be prohibited, which leads to either separate annotations for each standard or the current annotation `SupportedStandards` should take as input a list of enums of the fixed provided standards instead of a list of `String`.

If other standards are allowed that we don't know of, we need to provide `String` as input. Then we could provide both as you described.

**Comment by mialbu** [comment]
This has been implemented in pr #716.
