### ISSUE TITLE
Interact/Call smart contract's methods

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#41]
As a developer, I would like to use `neow3j` to invoke/call smart contract's methods using my local key pairs to sign the transaction. This would enable various use cases for the Java community of the NEO blockchain.

**Comment by nimmortal** [comment]
Upvote. This feature is important for dApps based on Java.

**Comment by claudemiller** [comment]
Closing this issue. The initial implementation is complete. For further developments in this area feedback from the community is needed. New issues on the topic can then be opened.
