### ISSUE TITLE
Is there a way to create smartcontract where the totalsupply handle number bigger than int ? 

### ISSUE THREAD

**Issue by djm34** [neow3j/neow3j#420]
Hello,

I have been trying to create a smartcontract with total supply handling 8 decimals, however it seems that devpack prevent the use of BigInteger and if I use 8 decimals, in the smartcontract I end up with 10 coins in the smartcontract. 

I read that devpack wasn't supporting BigInteger, but is there an away to have larger totalsupply anyway ?
Thanks for your help
djm34

**Comment by csmuller** [comment]
Hey @djm34

As you mentioned we deliberately don't support `BigInteger` at the moment. Our goal was to cover all numbers with Java's int type. Your question shows that this decision leads to a bit of confusion, i.e., we might consider adding `BigInteger` support in the future.
For now you can use the following for large integers. 
```java
static final int initialSupply = StringLiteralHelper.stringToInt("100000000000000000");
```
This example is from a contract that has 100'000'000 tokens which are divisible with 8 decimals. This leads to the number of  100'000'000 * 100'000'000 = 100'000'000'000'000'000 token fractions.

So, whenever you need to state an integer that is larger than Java's int type, you can use StringLiteralHelper.stringToInt(...).

**Comment by djm34** [comment]
ah ok :) 
I was a bit under the impression that the stringToInt method would truncate the number, or things would get truncated when doing the operation with int. (if not, I don't think the BigInteger type is really needed)
