### ISSUE TITLE
Make the handling of endianness in hashes (e.g. script hashes) uniform

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#442]
The Hash160 and Hash256 classes store the hash values as a little endian byte array but when `toString()` is called the value is returned as big-endian. Make this uniform and use only one byte ordering (I lean towards big-endian because that is how Java mostly handles binary values).

Additionally, check for the usage of hashes throughout neow3j and make sure that their endianness is consistent and well documented.

Check the Neo documentation about endianness [here](https://docs.neo.org/v3/docs/en-us/basic/concept/endian.html).

**Comment by mialbu** [comment]
Currently this blocks the class `TransactionSigner` from changing its account from `String` to `Hash160`. When serializing, the signer's script hash is reversed.
The same is the case for the variable `asset` of the class `TransactionSendAsset`.

**Comment by mialbu** [comment]
This was done in pr #492.
