### ISSUE TITLE
Discuss about the necessity of wrapper classes for the new native contracts StdLib and CryptoLib

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#452]
See according commit in the Neo core [here](https://github.com/neo-project/neo/commit/9fe018c6617887534eb9f9573bde1a8509055b6e).

**Comment by csmuller** [comment]
The CryptoLib contract provides crypto functionality and the StdLib encoding and decoding as well as serialization functionality. This can all be done locally by a client. Adding a wrapper for these two contracts to the neow3j SDK does not make sense.
