### ISSUE TITLE
Remove getContract from the ContractManagement wrapper class

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#470]
The `getContract` method doesn't provide more information than the `getcontractstate` RPC method. Furthermore, the two ways of retrieving contract information slightly deviate in the returned format, leading to extra fields in the `ContractState` class.

We propose to remove the `getContract` method from the `ContractManagement` wrapper class. It is meant for usage in smart contracts but not necessarily for calls from a client.
This would make the changes from #404 obsolete.

- [x] Remove the method and its tests
- [x] Adapt the `ContractState` class to fit solely the `getcontractstate` and `getnativecontracts` RPC methods.
- [x] Remove the PR #404

**Comment by mialbu** [comment]
This was done in pr #490.
