### ISSUE TITLE
Remove deserializer in ContractParameter class

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#473]
Neow3j has a separate deserializer for ContractParameters. This would only be used if a parameter should be read from a JSON string.

Either the deserializer should be removed completely, or tests should be added as well as the missing deserialization for Map contract parameters.

> Note: The RPC calls that return a map are covered in the class `StackItem`.

**Comment by gsmachado** [comment]
Decision: remove the deserializer.

**Comment by mialbu** [comment]
This was done in pr #502.
