### ISSUE TITLE
Add a NonFungibleToken class to the devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#474]
The neow3j SDK supports a NFT wrapper, but the devpack is lacking that support.
It makes sense to add an NFT class before implementing the NameService contract interface in the devpack since the NameService can be implemented as a subclass of NFT.

**Comment by csmuller** [comment]
Started work in branch https://github.com/neow3j/neow3j/tree/feature/devpack-nft-class.

**Comment by mialbu** [comment]
This was merged in pr #605.
