### ISSUE TITLE
Adapt the release process by using the new Gradle Nexus Publish Plugin

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#484]
Two plugins required for releasing to Nexus servers where merged recently into one new plugin, the [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin).

We should give it a try for our release process. It should allow us to automate publishing our artifacts via the Nexus Repository Manager.

**Comment by gsmachado** [comment]
@csmuller FYI: within this task, I will also remove all traces to the `bintray` from our Gradle files.

**Comment by gsmachado** [comment]
@csmuller @mialbu some things to be discussed:

1) Do you think that is useful to automatically publish SNAPSHOTS once we commit to `develop-3.x`? Now, we can do it without trouble! 🎉 
2) Do you think it makes sense to have a manual GitHub Action workflow to publish a release (automatically)? Or do we still prefer to do it manually, from the command line?

**Comment by csmuller** [comment]
> 1. Do you think that is useful to automatically publish SNAPSHOTS once we commit to `develop-3.x`? Now, we can do it without trouble! 🎉

Yes, i'm in favor of automatically publishing snapshots form the develop branch.

> 2. Do you think it makes sense to have a manual GitHub Action workflow to publish a release (automatically)? Or do we still prefer to do it manually, from the command line?

Depends on the effort of creating such an GitHub Action. It's nice to have it, but if it is not easy to get it done than publishing from the command line is also fine.

**Comment by gsmachado** [comment]
> Yes, i'm in favor of automatically publishing snapshots form the develop branch.

Great! Yes, I also think it's good.

So, two more questions;

1. Should we then ALWAYS bump the version of neow3j right after the release and commit to develop? For example, we should have `3.9.0` version right now in our `build.gradle`, instead of the current (and already released) version `3.8.0`.
2. Instead of uploading to the SNAPSHOT repo every time we commit to `develop-3.x` we could also trigger based on manual actions. Then we could use that for smoke tests before releasing, etc. What do you think?

> 
> Depends on the effort of creating such an GitHub Action. It's nice to have it, but if it is not easy to get it done than publishing from the command line is also fine.

Hmm... thinking a bit better, this is not prior at the moment. I will not do that.

**Comment by csmuller** [comment]
> Should we then ALWAYS bump the version of neow3j right after the release and commit to develop? For example, we should have 3.9.0 version right now in our build.gradle, instead of the current (and already released) version 3.8.0.

Yes that seems to be the right way to go.

> Instead of uploading to the SNAPSHOT repo every time we commit to develop-3.x we could trigger based on manual actions. Then we could use that for smoke tests before releasing, etc. What do you think?

Since I see no real need for regular SNAPSHOTs, we can definitely make it a manual process.
