### ISSUE TITLE
Change dependencies from 'compile' to 'implementation'

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#485]
The `compile` directive that we use in all our `build.gradle` files is depricated. We should replace it with `implementation`. Equally for the `compileTest` that should be replaced by `implementationTest`.

The advantage of `implementation` is that it avoids that dependencies of our library are transitively passed on to the user. So if the dev depends on `io.neow3j:devpack`, the dependencies of the devpack do not show up in the dev's classpath. Or, if someone needs the `contract` and the `core` package, they have to depend on both explicitly.

This includes changing the README.md in this repo and the external documentation, where we usually say that you only need to import `contract` to also get `core`.

**Comment by gsmachado** [comment]
hmmmm.... while thinking and changing code for this issue, I questioned myself: is this a good idea?

**Comment by csmuller** [comment]
I think it makes sense for the `devpack`. The devpack depends on `contract` but we don't want classes of `contract` and `core` show up as recommendations when the dev is implementing a smart contract. That should be preventable by applying the above mentioned dependency configuration.

Furthermore, it seems the right approach to not clutter the devs classpath with transitive dependencies.

**Comment by gsmachado** [comment]
Agreed. The problem is that this can't be applied for some dependencies (mainly in the `core`).

But I agree that the main use case is for the `devpack`. 👍

**Comment by csmuller** [comment]
Resolved in #620.
