### ISSUE TITLE
Provide a test framework

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#486]
Users of neow3j should be able to easily write automated tests for their Java smart contracts. Currently we internally use a `TestRule` that automates many things for us in our tests of the devpack and compiler. The same or something similar should be provided for the developer.

Check out the testing capabilities of the visual-tracker first.

**Comment by gsmachado** [comment]
Maybe we should explore the feasibility of having a Java wrapper (classes) for Neo Express.

- Neo Express will be installed/running in a docker image
- neow3j wrapper to send `exec` commands to the running docker image

The reason to send `exec` commands is that Neo Express doesn't have a JSON-RPC interface for all those commands.

**Comment by gsmachado** [comment]
Check this thread: https://twitter.com/DevHawk/status/1386795714403962883

**Comment by gsmachado** [comment]
@devhawk confirmed that `neo-express` exposes all commands through JSON-RPC!

I will make a map fo all calls we should support. This gives us a good foundation to the test framework for neow3j. 😄

**Comment by gsmachado** [comment]
@csmuller this issue was kind of "bootstrapped" by you already, right... I will set it to "In Progress" then.

**Comment by csmuller** [comment]
Other features that could be added:
- [ ] Neo-specific asserts
- [ ] The possibility of applying a batch or checkpoint file on per-test basis

**Comment by csmuller** [comment]
The test framework is in a good state now. Thus, this issue can be closed. The above check list can be tackled in other issues in the future.
