### ISSUE TITLE
Refactor RPC methods

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#493]
#### Problem:
There are several RPC call methods that use addresses as parameters. Currently neow3j handles these as `String` and does not check whether it is a valid address before sending an RPC request. This results in the node returning the error message `Invalid params`, which is not be very specific, especially in method calls with many parameters.

#### Solution Suggestion:
A separate class `Address` for Neo addresses could enforce correct addresses before any request is sent.

**Comment by csmuller** [comment]
What about doing valid address checks in all of these rpc calls instead of a new class?

**Comment by gsmachado** [comment]
> What about doing valid address checks in all of these rpc calls instead of a new class?

Honestly, I would prefer going to this direction. Reason: we already have several specific classes for multiple things.

I know that we need to provide reliability and correctness (decrease risk of errors) on one hand, but we should provide a good and simple developer experience on the other's hand.

However, I'm open to further discussing it.

**Comment by mialbu** [comment]
> What about doing valid address checks in all of these rpc calls instead of a new class?

Yes, we could do this as well. Although, addresses are also used in other cases, e.g. in the class `TransactionSendAsset` where it is also "just" a String. I think adding a small separate class could still avoid doing validity checks wherever we need addresses...

**Comment by csmuller** [comment]
We could replace the use of address strings with `Hash160` and use `Hash160.toAddress()` internally in these methods. Then we don't need a new class and we have the checks already included in `Hash160`.

**Comment by mialbu** [comment]
> We could replace the use of address strings with `Hash160` and use `Hash160.toAddress()` internally in these methods. Then we don't need a new class and we have the checks already included in `Hash160`.

I like that approach. @gsmachado what do you think about this?

**Comment by gsmachado** [comment]
@mialbu yes, I agree with that! I think we can proceed with that solution for now.

**Comment by gsmachado** [comment]
Should we include this in the next milestone? Or this doesn't have so high prio?

What do you think?

**Comment by csmuller** [comment]
It doesn't have a high priority in my opinion but it fits well with other maintenance tasks in this milestone, like #480 or #473.

**Comment by gsmachado** [comment]
@csmuller yes, agree.

Could we try to squeeze this issue to this milestone as well, @mialbu? if yes, please set the milestone appropriately and put to ToDo. 😄

**Comment by mialbu** [comment]
This was done in pr #503.
