### ISSUE TITLE
RPC calls sendMany and sendFrom should not allow amounts as decimal

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#494]
#### Problem:
The RPC methods `sendMany` and `sendFrom` currently allow Strings for the amount. If a decimal number is passed, the node just returns the error message `Invalid params`. (Currently there is even a test in the `RequestTest` that contains such an example - which in reality does not work...)

E.g. using the RPC call `sendFrom`, the following returns the error `Invalid params`:

```
{
    "jsonrpc": "2.0",
    "method":"sendfrom",
    "params": [
        "0xd2a4cff31913016155e38e474a2c06d08be276cf",
        "NKvR5WeczCQMcVWQD9aaMqegfEoCBXGWpW",
        "NUrPrFLETzoe7N2FLi2dqTvLwc9L2Em84K",
        "10.0"
    ],
    "id": 1
}
```

but this does:

```
{
    "jsonrpc": "2.0",
    "method":"sendfrom",
    "params": [
        "0xd2a4cff31913016155e38e474a2c06d08be276cf",
        "NKvR5WeczCQMcVWQD9aaMqegfEoCBXGWpW",
        "NUrPrFLETzoe7N2FLi2dqTvLwc9L2Em84K",
        "10"
    ],
    "id": 1
}
```

> A call where the amount is `10` instead of `"10"` also works.

#### Solution Suggestion:
To circumvent this, I suggest changing the amount to a `BigInteger`.

or

The current method remains in order to not change the existing api and just let it call a new method that takes a `BigInteger` as the amount parameter. In that case the validity of the provided string is checked before sending the RPC call.

> I prefer the second option because it only extends the api.

**Comment by csmuller** [comment]
Good point!
I don't mind replacing the method with one that has `BigInteger` as the parameter since we will anyway have breaking changes again in the next release.

**Comment by gsmachado** [comment]
Yes, great point.

I think we should have a `BigInteger` type as param, yes.

**Comment by mialbu** [comment]
This was done in pr #503.
