### ISSUE TITLE
Make handling of token amounts uniform

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#505]
#### Problem:

In the past there was a short time when Neo handled decimal numbers for gas costs or transfer amounts in RPC responses (e.g. in the RPC ´calculatenetworkfee´). This lead to adapting the use of BigDecimals in neow3j.

Currently there are methods in neow3j that handle amounts in token fractions (BigInteger) and methods that handle decimal numbers (BigDecimal) which can be misleading.

E.g. the transfer methods in the `FungibleToken` expect the transfer amount with decimal points as a `BigDecimal`, whereas the methods `getBalanceOf()` in the same class returns the balance in fractions as a `BigInteger`.

#### Suggestion

We should stick to one way of handling amounts in neow3j.
I'd suggest to work with BigIntegers (token fractions) and refactor every method that is currently handling amounts with decimal points. This would align neow3j with Neo, where now everything is handled without decimal numbers.

**Comment by gsmachado** [comment]
@mialbu I agree we should make this uniform across the whole repo.

What's the effort of doing this? Like hours or multiple days?

**Comment by mialbu** [comment]
Great.

> What's the effort of doing this? Like hours or multiple days?

I haven't checked the full extent of it but I think this would take maximum one day.

**Comment by gsmachado** [comment]
> I haven't checked the full extent of it but I think this would take maximum one day.

My vote is: if it takes one single day, I would do it asap.

What's your opinion, @csmuller, in terms of priority?

**Comment by mialbu** [comment]
This was merged in pr #509.
