### ISSUE TITLE
Add Storage getters that automatically convert the return type

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#513]
The `Storage` class of the devpack provides getters that all return a `ByteString`. It is up to the user to convert that return type to anything else.
We should consider adding getter methods that automatically do a conversion.
E.g.: `public static native int Storage.getInt(StorageContext ctx, BytesString key)`

Such methods would require the appropriate conversion to be added on the method with the `@Instruction` annotation.

**Comment by mialbu** [comment]
This issue is currently blocked and relies on #559.

**Comment by mialbu** [comment]
This issue is no longer blocked, according to [this comment](https://github.com/neow3j/neow3j/issues/559#issuecomment-887492802).

**Comment by csmuller** [comment]
Resolved by #587.
