### ISSUE TITLE
Small Switch-Case with String fails to compile

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#519]
Switch-case statements working on a string and having less than three cases fail on compilation. The structure of the byte code must be different than what expected in the compiler.

**Comment by gsmachado** [comment]
😨

**Comment by gsmachado** [comment]
@csmuller this is related to #520 right?

If yes, can we close it now?

**Comment by gsmachado** [comment]
This is still an issue, correct?

**Comment by csmuller** [comment]
yes

**Comment by csmuller** [comment]
Solved in #551.
