### ISSUE TITLE
Add a "Features" annotation to the devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#539]
Since Neo N3 RC2, the contract manifest has an extra property called `features`.  The devpack should have an annotation that allows the dev to set this property.

**Comment by mialbu** [comment]
The features in the contract manifest are still meant to be empty as specified in the [NEP-15](https://github.com/neo-project/proposals/blob/0a76fa0c6d9102cd46ddbcd79e58f38246188a8e/nep-15.mediawiki):
`The features field will be used for future expansion and should always be an empty object for now.`

I will move this issue to blocked in the neow3j-development and remove it from the september milestone.

**Comment by mialbu** [comment]
Imo, we can close this and just reopen if there will be an update to the NEP-15 that includes updates to the `features` field.

**Comment by gsmachado** [comment]
> Imo, we can close this and just reopen if there will be an update to the NEP-15 that includes updates to the `features` field.

Agreed. Let's close this one. 💪
