### ISSUE TITLE
Compile error: String concatentation

### ISSUE THREAD

**Issue by ykoitzsch** [neow3j/neow3j#546]
Compiling the class below throws an exception

```
public class HelloWorld {
    
    public static String hello(String arg1, String arg2) {
        return arg1 + arg2;
    }
}
```

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at org.objectweb.asm.tree.InsnList.get(InsnList.java:94)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:486)
        at io.neow3j.compiler.converters.MethodsConverter.handleUncachedMethodCall(MethodsConverter.java:193)
        at io.neow3j.compiler.converters.MethodsConverter.handleMethodCall(MethodsConverter.java:167)
        at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:148)
        at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:81)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.converters.ObjectsConverter.handleStringConcatenation(ObjectsConverter.java:301)
        at io.neow3j.compiler.converters.ObjectsConverter.handleNew(ObjectsConverter.java:167)
        at io.neow3j.compiler.converters.ObjectsConverter.convert(ObjectsConverter.java:83)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:488)
        at io.neow3j.compiler.converters.MethodsConverter.handleUncachedMethodCall(MethodsConverter.java:193)
        at io.neow3j.compiler.converters.MethodsConverter.handleMethodCall(MethodsConverter.java:167)
        at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:148)
        at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:81)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:488)
        at io.neow3j.compiler.converters.MethodsConverter.handleUncachedMethodCall(MethodsConverter.java:193)
        at io.neow3j.compiler.converters.MethodsConverter.handleMethodCall(MethodsConverter.java:167)
        at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:148)
        at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:81)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.converters.ObjectsConverter.handleStringConcatenation(ObjectsConverter.java:301)
        at io.neow3j.compiler.converters.ObjectsConverter.handleNew(ObjectsConverter.java:167)
        at io.neow3j.compiler.converters.ObjectsConverter.convert(ObjectsConverter.java:83)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:488)
        at io.neow3j.compiler.Compiler.compile(Compiler.java:271)
        at io.neow3j.compiler.Compiler.compile(Compiler.java:240)
        at io.neow3j.examples.contractdevelopment.CompileAndDeploy.main(CompileAndDeploy.java:26)

```

**Comment by gsmachado** [comment]
Hello @ykoitzsch 

Thanks for the issue!

So, could you quickly test the same smart contract but using the `3.10.0-SNAPSHOT`? We started to publish SNAPSHOTs once in a while. This enables us to test some functionalities without officially releasing and collect feedback.

Instructions on how to use the SNAPSHOT in your Gradle project are described [here](https://github.com/neow3j/neow3j/blob/develop-3.x/DEVELOPMENT.md#using-the-snapshot-versions).

Please, post here if the compilation issue remains.

**Comment by gsmachado** [comment]
@ykoitzsch ok, I could confirm that we still have this problem (current `develop-3.x` branch). I've made some tests demonstrating the problem (that at the moment are failing). We'll fix asap.

**Comment by csmuller** [comment]
Hey @ykoitzsch, I was not able to reproduce the exception with you code. I tried with neow3j 3.9.0 release and our current develop branch. I assume you used 3.9.0 as well, right?

Hmmm i'm a bit clueless what the problem could be... 
What java version are you using?
Can you post the class file of the compiled class here? There should be a *build/classes* directory in your project directory and somewhere in there you should be able to find the class file.

**Comment by gsmachado** [comment]
Hello @ykoitzsch 

[neow3j 3.10.0](https://github.com/neow3j/neow3j/releases/tag/3.10.0) is released! 🎉 

Please, try to reproduce this issue with 3.10.0 and give us feedback.

If the problem remains, please, re-open this issue and we'll further analyze it. 😄

**Comment by ykoitzsch** [comment]
Hey @gsmachado
that's great news! Unfortunately I am still running into this issue. I will add the compiled class file to this post @csmuller .
I am working with java 11.

[StringConcatContract3.class.zip](https://github.com/neow3j/neow3j/files/6510418/StringConcatContract3.class.zip)

I also did some more testing, the compile error only happens when I concatenate 2 string variables like in bongoCat2() and bongoCat3().

```
    public static String bongoCat() {
        return "neowwwwwwwwww" +  "something else";
    }

   /*  public static String bongoCat2(String arg1, String arg2) {
        return arg1 +  arg2;
    } */

    public static String bongoCat3String() {
        String arg1 = "hello";
        String arg2 = "world";
        return arg1 +  arg2;
    }
```

**Comment by gsmachado** [comment]
Alright. I'm re-opening the issue.

**Comment by ykoitzsch** [comment]
Very strange, now I am getting the same error here:
```
public class Foo {
    
    public static String bongoCat() {
        return Runtime.getExecutingScriptHash().toString();
    }
}
```
So it's not solely related to the problem I described above ill do some more research tomorrow. But for now I am left confused :disappointed:

**Comment by csmuller** [comment]
So, the problem is the bytecode that your java compiler produced is different of what neow3j expects and what our compilers produce. Interesting to see such differences. 

@ykoitzsch What JDK are you using? From what vendor, OracleJDK, OpenJDK, or even something else?

**Comment by ykoitzsch** [comment]
I am using the OpenJDK 11.0.11

**Comment by gsmachado** [comment]
@ykoitzsch since we can't reproduce it, could you kindly share a .zip file with the entire project (gradle + sources)? Just .zip the dir.

**Comment by csmuller** [comment]
When doing string concatenation, the Java compiler transforms the `+` operation into the construction of a `StringBuilder` and one or more calls to its `append(...)` method. Now, I'm clueless to why, in the class file you provided, the compiler makes a call to `String.valueOf(Object obj)` before calling the `StringBuilder` constructor. The `String` is already a string, why does it call `String.valueOf` 🤔 

As Guil said, would be cool if you could zip the whole project folder and post it here or on discord.

**Comment by ykoitzsch** [comment]
[neow3j-examples-java.zip](https://github.com/neow3j/neow3j/files/6517146/neow3j-examples-java.zip)

**Comment by csmuller** [comment]
I don't see any anomalies. It seems that your java compiler simply produces different byte code than what we have seen so far. That's ok. But the problem is, that i'm in the dark when trying to handle your compiler output because I cannot produce it myself.

Can you send me the compiled .class file of the following contract. I'm curious to see what byte code your compiler will produce for this source code.

```
public class ExampleContract {

    public static String test() {
        ByteString x = new ByteString("x");
        String y = "y";
        return x + y;
    }
}
```

**Comment by gsmachado** [comment]
@ykoitzsch besides answering the question above, from @csmuller, can you tell us which operating system you're using (and the version)?

**Comment by ykoitzsch** [comment]
Sure, no problem: 
[ExampleContract.class.zip](https://github.com/neow3j/neow3j/files/6526595/ExampleContract.class.zip)

@gsmachado Ubuntu 20.04.1 LTS

**Comment by gsmachado** [comment]
> [neow3j-examples-java.zip](https://github.com/neow3j/neow3j/files/6517146/neow3j-examples-java.zip)

Hello @ykoitzsch 

I spent some time to try to reproduce your issue with the concatenation, and I couldn't! 🤔 😮 

I downloaded Ubuntu 20.04, Desktop edition. Then, I installed AdoptOpenJDK, version 11.0.11 (exactly as you described).

After that, I took the [neow3j-examples-java.zip](https://github.com/neow3j/neow3j/files/6517146/neow3j-examples-java.zip) file you posted here, uncompressed in the home directory.

In the project, I could see the class `neow3j-examples-java/neo-n3-examples/src/main/java/io/neow3j/examples/contractdevelopment/contracts/myexamples/StringConcatContract.java`:

```java
package io.neow3j.examples.contractdevelopment.contracts.myexamples;

// A simple smart contract with one method that returns a string and takes no arguments.
public class StringConcatContract {
    
    public static String test() {
        String x = "a";
        String y = "b";
        return x+y; 
    }
}
```

So... I opened the `build.gradle` file, and set the following:

```
neow3jCompiler {
     className = "io.neow3j.examples.contractdevelopment.contracts.myexamples.StringConcatContract"
     debug = true
}
```

just that it compiles the right class. 😄 

Then, I simply executed:

```bash
sh gradlew clean neow3jCompile
```

and the output was:

![image](https://user-images.githubusercontent.com/2124276/119265795-3e7b3200-bbe8-11eb-92ec-936c4c1d52f4.png)

It succeeds! 🚀 

Then... I went a bit further and tried to modify a bit the `StringConcatContract.java`, just to make sure we cover all things you pointed in this issue:

```java
package io.neow3j.examples.contractdevelopment.contracts.myexamples;

import io.neow3j.devpack.ByteString;

// A simple smart contract with one method that returns a string and takes no arguments.
public class StringConcatContract {
    
    public static String test() {
        String x = "a";
        String y = "b";
        return x+y; 
    }

    public static String hello(String arg1, String arg2) {
        return arg1 + arg2;
    }

    public static String bongoCat() {
        return "neowwwwwwwwww" +  "something else";
    }

    public static String test2() {
        ByteString x = new ByteString("x");
        String y = "y";
        return x + y;
    }
}
```

I tried again to `sh gradlew clean neow3jCompile` and the result was the same: `Compilation succeeded!`, generating the NEF, Manifest, and Debug Info files.

I wonder: what are we doing differently?

**Comment by ykoitzsch** [comment]
Oh I see! I think the issue is that I am always compile/deploying my contracts with the provided CompileAndDeploy.java class.

**Comment by gsmachado** [comment]
> Oh I see! I think the issue is that I am always compile/deploying my contracts with the provided CompileAndDeploy.java class. I tried using the gradle task and this works just fine.

That's super valuable feedback! 👍 

I will try to use the `CompileAndDeploy.java` and will let you know where the problem lies. However, the problem with the `CompileAndDeploy.java` is that it doesn't enforce compiling with the Java 1.8 target (which is required for the neow3j compiler).

@ykoitzsch one more question: can you please post the output of the `java -version` command on your machine?

I was wondering what kind of AdopOpenJDK flavor you were using... there is, e.g., the `hotspot`, `openj9`, and others...

**Comment by ykoitzsch** [comment]
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by gsmachado** [comment]
@ykoitzsch 

Alright. Thanks for the discussion. This helped us quite a bit. 😄  👍 

I created #553 to provide a better compilation message when Java version higher than 8 is provided. 💪
