### ISSUE TITLE
Wallet.create() generates infinite accounts inside

### ISSUE THREAD

**Issue by bettybao1209** [neow3j/neow3j#552]
![image](https://user-images.githubusercontent.com/12050350/119112355-91bd7b00-ba56-11eb-8416-72024cfe0175.png)

Something weird happens. When I use the `Wallet.create()` method to create a wallet，it generates lots of the same accounts recursively.

**Comment by mialbu** [comment]
Hi @bettybao1209,

This is actually a circular reference in the design of our `Wallet` and `Account` classes. Every account is linked to its containing wallet.

As you can see, the object references of the first wallet (`Wallet@8808`) and its list of accounts (`HashMap@8818`) are the same in the recurring wallet, which means that it's the exact same wallet again.

**Comment by bettybao1209** [comment]
> Hi @bettybao1209,
> 
> This is actually a circular reference in the design of our `Wallet` and `Account` classes. Every account is linked to its containing wallet.
> 
> As you can see, the object references of the first wallet (`Wallet@8808`) and its list of accounts (`HashMap@8818`) are the same in the recurring wallet, which means that it's the exact same wallet again. There is nothing actually generated additionally.

So how can I get the account info, since `wallet.getAccounts().get(0)` does not work.

**Comment by mialbu** [comment]
> So how can I get the account info, since `wallet.getAccounts().get(0)` does not work.

I cannot reproduce this.

What neow3j version and what Java version are you using (and adoptOpenJdk or Oracle)?

**Comment by bettybao1209** [comment]
> > So how can I get the account info, since `wallet.getAccounts().get(0)` does not work.
> 
> I cannot reproduce this.
> 
> What neow3j version and what Java version are you using (and adoptOpenJdk or Oracle)?

I use `neow3j version 3.10.0` and `openjdk version 11.0.9.1`

**Comment by mialbu** [comment]
> ![image](https://user-images.githubusercontent.com/12050350/119120403-cf260680-ba5e-11eb-9488-1ef596f46290.png)

Hmm, I see. Let me discuss that internally, I'll come back to you.

**Comment by bettybao1209** [comment]
> > ![image](https://user-images.githubusercontent.com/12050350/119120403-cf260680-ba5e-11eb-9488-1ef596f46290.png)
> 
> Hmm, I see. Let me discuss that internally, I'll come back to you.

Ok, thanks~

**Comment by bettybao1209** [comment]
My case is to store the newly created wallets into the db, I switch to using the NEP6Wallet which works well. So I will close this issue.
