### ISSUE TITLE
Improve storage-related classes

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#559]
There are several improvments we can make for the devpack's storage classes:
- [x] Remove the `createMap(...)` methods from `StorageContext` and add corresponding constructors to the `StorageMap` class. This removes an intermediate method and method call from the contract script. It's also more intuitive to use the constructor in my opinion.
- [x] Replace all method bodies in `StorageMap` with annotations exclusively. This removes another method and call from the script and replaces it with inline instructions.
  - [x] This requires that `@Instruction` and `@Syscall` annotations can be used at the same time on a method.
- [x] Add `getBoolean` methods to `Storage` and `StorageMap`

**Comment by gsmachado** [comment]
Is this something we could have the capacity to do it soon? Or not prio atm?

Just asking because it's blocking #587 for some time.

**Comment by csmuller** [comment]
This is not blocking #587 anymore. The last subtask was solved in PR #609.
Though, according to the neow3j proposal for Q3 and Q4 this is not a task for the July milestone.

**Comment by mialbu** [comment]
This was resolved in pr #706.
