### ISSUE TITLE
[develop-2.x] account balance does not contain the NEOAsset.HASH_ID

### ISSUE THREAD

**Issue by bettybao1209** [neow3j/neow3j#566]
![image](https://user-images.githubusercontent.com/12050350/120207940-96a4da80-c25f-11eb-9f7a-235b24539a91.png)
 I follow the guide to add the `output` while it throws the error `Account balance does not contain the asset with ID c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b`
 Am I using it in a wrong way?

**Comment by csmuller** [comment]
This problem was solved by calling `account.updateAssetBalances(neow3j)` before constructing the transfer.

**Comment by bettybao1209** [comment]
> This problem was solved by calling `account.updateAssetBalances(neow3j)` before constructing the transfer.

Yes, exactly. Fixed~
