### ISSUE TITLE
Specific NeoVM exceptions are not recoverable

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#567]
**Description**

Try-catch blocks only support unspecific `Exception`. However, when an exception is thrown in the NeoVM (e.g. `InvalidOperationException`) there is no way to catch that exception.

**To Reproduce**

1. Deploy a contract that contains the following method:

```java
public static void mint(ByteString tokenId, Map<String, String> properties) throws Exception {
        StorageContext ctx = Storage.getStorageContext();
        try {
            String tokenName = properties.get("name");
            ctx.createMap((byte) 12).put(tokenId, tokenName);
        } catch (Exception e) {
            throw new Exception("The properties must contain a value for the key `name`.");
        }
        try {
            String description = properties.get("description");
            ctx.createMap((byte) 13).put(tokenId, description);
        } catch (Exception ignored) {
        }
}
```
 
> **Note:** The parameter `properties` is intended to have a required key `name` and an optional key `description`.

2. Invoke the method with a `properties` map that only contains one key-value pair with the key `name`.
3. The NeoVM throws an `InvalidOperationException` exception in the opcode `PICKITEM` when trying to get the key-value pair for the key `description`. This exception cannot be caught and the transaction faults.

**Environment:**

 - MacOS v10.15.7
 - N3 - RC2 ([AxLabs' N3 privatenet](https://github.com/AxLabs/neo3-privatenet-docker))

**Expected behaviour**

Either all exceptions that may be thrown in the NeoVM should be caught by the described example catch clause, or those specific exceptions should be supported, so that they can be handled.

**Comment by csmuller** [comment]
I took a look at the VM and found that the `InvalidOperationException` that you get at the `PICKITEM` instruction is not a contract-level exception that could be caught within the contract. Rather, it is a VM-level exception that leads to a FAULT state that cannot be called.

The solution for your example is to use `properties.containsKey("description")` before calling `get`.

I think it is worth opening an issue that asks for "catchability" of the `InvalidOperationException` thrown in this case.

**Comment by csmuller** [comment]
I opened this discussion about this topic on the NeoVM repo: https://github.com/neo-project/neo-vm/issues/414
