### ISSUE TITLE
Wallet: method for creating a new wallet and account

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#57]
As a developer, I would like to have a method (maybe, static) on the `Wallet` class to create a wallet with an account already on it.

For example, like this a wallet object is created with an account already added to it:

```
Wallet w1 = Wallet.create();
```

Or, you can create a wallet object and already persist to a NEP6-compatible .json file, like:

```
Wallet w1 = Wallet.create("/tmp/wallet.json");
```

**Comment by claudemiller** [comment]
The above commits resolve the first part of the issue but not the second (creation with writing the wallet to a file immediately).
