### ISSUE TITLE
RC3 Update

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#571]
- [x] Add `base58CheckEncode` and `base58CheckDecode` to class `StdLib` ([pr](https://github.com/neo-project/neo/pull/2468))
- [x] Add `getAccountState` to class `NeoToken` in devpack module ([pr](https://github.com/neo-project/neo/pull/2475))
- [x] Add `getAccountState` to class `NeoToken` in contract module ([pr](https://github.com/neo-project/neo/pull/2475))

**Comment by gsmachado** [comment]
@mialbu anything else changed for the devpack?

**Comment by mialbu** [comment]
> @mialbu anything else changed for the devpack?

No, that should be all.

**Comment by mialbu** [comment]
This was merged in pr #580.
