### ISSUE TITLE
Support invocation script for contract signers

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#589]
When creating a transaction that has a contract as a signer the transaction builder attaches an empty witness to the transaction before calling the `calculatenetworkfee` RPC to fetch the network fee. The empty witness only works if the contract's `verify` method has no parameters. If it has parameters, an invocation script packing those parameters is required in the witness.
The `TransactionBuilder` does not provide this possibility at the moment. Thus, neow3j only allows for `verify` methods without parameters.

We need to come up with a design that allows attaching an invocation script.

**Comment by mialbu** [comment]
This was merged in pr #600.
