### ISSUE TITLE
Rework the TransactionBuilder by removing the Wallet property

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#603]
We should consider removing the wallet from the `TransactionBuilder`.  It makes the builder less intuitive. When developers add a signer to the builder and provide the signers account, why should they also have to pass the wallet when the account already contains the private key.

The only functionality that we loose is the automatic signing with a multi-sig address if all participating accounts are in the wallet. But, this is probably not a real-world use case anyway. Having all private keys of the multi-sig address in one wallet partly defeats the use of the multi-sig.

**Comment by mialbu** [comment]
This was merged in pr #627.
