### ISSUE TITLE
Add expressShutdown RPC to Neow3jExpress

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#611]
A RPC `expressshutdown` was recently added to Neo-express (see [neo-express:73a1161](https://github.com/neo-project/neo-express/commit/73a11615875ab834f1f978b57f7c496dc620e71d)).

`Neow3jExpress` instance should be extended to support this RPC.

This issue should only be taken, as soon as the next neo-express version that contains this RPC is released.

**Comment by csmuller** [comment]
Resolved in #610.
