### ISSUE TITLE
Add setter for Neow3j object in Transaction class

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#614]
**Problem:**

When exporting the transaction bytes (here referred to as `txBytes`) and reimporting them with `NeoSerializableInterface.from(txBytes, Transaction.class)`, the just created `Transaction` object cannot be used because its `Neow3j` object is `null` and there is no option to set it.

**Solution suggestion:**

Add a setter for the `Neow3j` object in the class `Transaction`.

**Comment by csmuller** [comment]
Resolved in #615.
