### ISSUE TITLE
Add convenience methods for building scripts

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#629]
The script of a transaction can contain multiple invocations. As from the pr #627, the wallet abstraction was removed from the TransactionBuilder and as such also from the FungibleToken class. That abstraction allowed to build a transaction that contained multiple token transfers (i.e. the transaction script was a concatenation of multiple invocation scripts).

Convenience methods should be provided, such that transaction scripts that contain multiple scripts (e.g. multiple transfer invocations) can easily be built.

- [x] ~A helper class should provide methods to concatenate scripts~ Add an additional method to append to the script in the class `TransactionBuilder`.
- [x] The wrapper classes in the contract module should provide methods to simply build a script (`byte[]`) for an invocation. A transaction script can then be built by extending the script with those built scripts.

**Comment by csmuller** [comment]
About the second point: So, you want to return a `byte[]`, i.e., the script instead of a `TransactionBuilder`?
