### ISSUE TITLE
Update getversion RPC method with protocol parameters

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#635]
See changes in https://github.com/neo-project/neo-modules/pull/639 as soon as the PR is done.

**Comment by gsmachado** [comment]
moving this issue to the next milestone.

**Comment by csmuller** [comment]
There is a TODO in `Neow3jReadOnlyIntegrationTest.java` that needs to be solved once the docker image we use for testing is up to date with the newest neo-node.

**Comment by csmuller** [comment]
Furthermore, a new PR popped up that adds the validator count to the getversion call (see https://github.com/neo-project/neo-modules/pull/642).

**Comment by csmuller** [comment]
Waiting for release of Neo 3.0.3 and a up-to-date test docker container to test the implementation.
