### ISSUE TITLE
getTransaction error

### ISSUE THREAD

**Issue by saahmadi** [neow3j/neow3j#638]
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class io.neow3j.protocol.core.response.TransactionAttribute]: missing type id property 'type' (for POJO property 'attributes')

**Comment by csmuller** [comment]
HI @saahmadi, I assume you tried to do `Neow3j.getTransaction(someTxHash)`. I need some more information about the transaction you tried to retrieve. Do you have a specific transaction hash on one of Neo's networks or did this happen on a private network you are working with?

**Comment by gsmachado** [comment]
Besides what @csmuller asked you above, can you also tell which neow3j version are you using? Thanks!

**Comment by gsmachado** [comment]
@saahmadi it seems that the transaction hash `cdc84b645ee68fdb62dc725c3bbd5dc53e05fc715ec7c645da11686429840938` is from [Neo Legacy](https://dora.coz.io/transaction/neo2/mainnet/cdc84b645ee68fdb62dc725c3bbd5dc53e05fc715ec7c645da11686429840938), and **not** from Neo N3.

If you want to use Neow3j SDK for Neo Legacy blockchain, then you need to use [neow3j 2.4.0](https://github.com/neow3j/neow3j/releases/tag/2.4.0) and **not** 3.13.0.

Please, check the [documentation](https://neow3j.io/#/neo-legacy/) of neow3j 2.4.0. There are some examples there.

**Comment by saahmadi** [comment]
thanks your guide it worked.
but now when i want to transfer some Neo with this code 

HttpService httpService = new HttpService("http://seed1.ngd.network:10332");

        neow3j = Neow3j.build(httpService);

Account fromAccount = Account.fromWIF("").build();

        fromAccount.updateAssetBalances(neow3j);

        System.out.println(fromAccount.getAddress());


           AssetTransfer transfer = new AssetTransfer.Builder(neow3j)
                   .account(fromAccount)
                   .output(NEOAsset.HASH_ID, 0.1, address)
                   .networkFee(0.001)
                   .build()
                   .sign()
                   .send();

it throw exception with message ->  Block or transaction validation failed.

**Comment by mialbu** [comment]
> but now when i want to transfer some Neo with this code
> 
> HttpService httpService = new HttpService("http://seed1.ngd.network:10332");
> 
> neow3j = Neow3j.build(httpService);
> 
> Account fromAccount = Account.fromWIF("").build();
> fromAccount.updateAssetBalances(neow3j);
> AssetTransfer transfer = new AssetTransfer.Builder(neow3j)
> .account(fromAccount)
> .output(NEOAsset.HASH_ID, 0.1, address)
> .networkFee(0.001)
> .build()
> .sign()
> .send();
> 
> it throw exception with message -> Block or transaction validation failed.

Hi @saahmadi, you are trying to transfer an amount of 0.1 of Neo. Neo is indivisible, so you can only transfer integer amounts of the Neo asset. I got to the same exception message as you did with 0.1 and when I replaced the amount with 1, the transaction was successful.

**Comment by mialbu** [comment]
I close this issue. Feel free to comment further if it still does not work or open a new issue for other problems that may arise.

**Comment by saahmadi** [comment]
> 
> 
> I close this issue. Feel free to comment further if it still does not work or open a new issue for other problems that may arise.

oh it`s was my fault thank you sir
