### ISSUE TITLE
Allow a wallet object as input to AssetTransfer and ContractInvocation

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#66]
As a developer I want to be able to execute an asset transfer or a contract invocation by providing a wallet instead of a single account. The library should on its own collect and create the necessary inputs and signatures required for a successful transaction by using any of the accounts in the wallet (e.g. the default account).

**Comment by gsmachado** [comment]
This issue is opened for such a long time, and even though it's a great feature to make developer's life easier, this is specific to Neo2 -- which is out of the scope at the moment.

If there's a concrete demand for this feature, we're happy to re-open and possibly implement it.
