### ISSUE TITLE
Support getMessage method on Exceptions

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#662]
**Summary or problem description**

When you catch an exception in a smart contract and want to get the message string with the `getMessage` method, the contract will fail at runtime. On the NeoVM the java `Exception` object is just the string that has been passed to the `Exception` constructor (or "error" when no string was provided). Thus, when calling `getMessage` on that string, the NeoVM fails.

**Do you have any solution you want to propose?**
Adapt the neow3j compiler such that calls to `Exception.getMessage()` are handled specially. In theory the call to `getMessage()` simply has to be ignored since the exception string is already at the top of the stack.

Tasks:
- [x] Adapt the compiler
- [x] Write integration tests in which exceptions are thrown (e.g., by assertions) and then the `Exception` object is handled in the `catch` clause by calling its `getMessage()` method.
- [x] Update the section Smart Contract Development -> NeowJava -> exceptions in the neow3j-docs.

**Comment by mialbu** [comment]
This was included in pr #669.
