### ISSUE TITLE
Add a deserialiser to ContractParameter

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#668]
**Summary or problem description**
Devs might want to use JSON ContractParameter representations to setup an invocation script with neow3j. We didn't foresee this use case and don't handle deserialisation in `ContractParameter` correctly.  The problem is, that if, e.g., a parameter of type Integer is deserialised, the ScriptBuilder fails at the moment because the integer is not converted to a BigInteger.

**Do you have any solution you want to propose?**
Add a custom deserialiser to the `ContractParameter` class. The deserialisation has to happen in a way that the ScriptBuilder doesn't run into problems when handling the deserialised parameters.

**Comment by bettybao1209** [comment]
ping.

**Comment by csmuller** [comment]
Resolved in #678.
