### ISSUE TITLE
Add getTransactionVMState method to LedgerContract

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#680]
A new method `getTransactionVMState` was added to the LedgerContract (https://github.com/neo-project/neo/pull/2628). Update neow3j devpack accordingly.

**Comment by csmuller** [comment]
This change is not in the Neo 3.1.0 release. Waiting for next Neo release.

**Comment by gsmachado** [comment]
Check comment: https://github.com/neow3j/neow3j/pull/685#issuecomment-985479568

This will be included in the next release.

**Comment by gsmachado** [comment]
@mialbu and what's the state about this issue?

FYI @csmuller

**Comment by mialbu** [comment]
It's blocked until the next Neo core release. Let's leave this as is and work on it as soon as the new release is out.
