### ISSUE TITLE
Add NEP-11 specific RPC methods

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#682]
The new Nep11Tracker adds two new RPC methods `getnep11transfers` and `getnep11balances.
- [x] Add those methods - and the required DTOs - to the Neow3j API.
- [x] Write tests in `ResponseTest` and `Neow3jReadOnlyIntegrationTest`.

No need to adapt the neow3j documentation. We don't mention every single RPC method there.

**Comment by gsmachado** [comment]
implemented on #688

**Comment by gsmachado** [comment]
I opened issue #690 to implement the integration tests in the future.
