### ISSUE TITLE
Automatic fetching of GAS consumption for contract invocations

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#69]
Already in NEO 2 one can test-run a contract invocation by calling the RPC methods `invoke` and `invokefunction`. But this fails if the invocation runs through a CheckWitness() statement in the invoked smart contract. As mentioned in this related [pull-request](https://github.com/neo-project/neo/pull/335) this problem will probably not be resolved in NEO 2 anymore. But it is planned for NEO 3.

Therefore, with NEO 3 the automatic fetching of the GAS consumption of a contract invocation can be implemented. This is a part of the `ContractInvocation` class and the necessary code is already available but commented out and not covered by tests.

**Comment by chenquanyu** [comment]
The system fee in ContractInvocation can be gotten by sending RPC "invokescript".

**Comment by csmuller** [comment]
For this to work in Neo 3 we depend on [this issue](https://github.com/neo-project/neo-modules/issues/212) to be solved.

**Comment by csmuller** [comment]
Resolved for Neo 3 by #120.
