### ISSUE TITLE
Extend ContractParameter.mapToContractParameter(...) to handle nested Lists and Maps

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#700]
When creating an Array or Map contract parameter one can pass a generic Java Map or List and the class will try to derive the correct Contract Parameter type for its contents. The corresponding method does not yet handle Maps and Lists within Maps and Lists, i.e., no recursion. Add such functionality.

- [x] Add functionality to handle the conversion of nested Maps and Lists to a ContractParameter.

Additionally
- [x] Add ECPublicKey to the handled objects and look for other types that we could add to the `mapToContractParameter` method.
- [x] Add a `ContractParameter.publicKey` static method that takes an `ECPublicKey`.

**Comment by mialbu** [comment]
This has been implemented in pr #713.
