### ISSUE TITLE
Improve Hash160, Hash256 and ECPoint

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#703]
The three classes represent special concepts in Neo but don't have separate stack item types on the NeoVM. They are all represented by a ByteString stack item. Though, these classes are handy for writing smart contracts mostly because of readability.

In all three, the constructors enforce the format of these types. E.g., when the developer instantiates a `Hash160` from a `ByteString` the compiler adds some instructions that check if the byte string is of the correct length. This assumes that the developer did not check this themselves. Even if the dev has previously used `Hash160.isValid(...)` on the byte string before these instructions are inserted. I think that is not intuitive. The constructors should not enforce anything and we should leave it to the dev to make checks on method arguments that might not have the desired format.

- [x] Remove checks from constructors of `Hash160`, `Hash256`, `ECPoint`
- [x] Add `isValid` method to `ECPoint`.

**Comment by mialbu** [comment]
This has been implemented in pr #709.
