### ISSUE TITLE
The use of compressPublicKey.

### ISSUE THREAD

**Issue by Yangxin-GG** [neow3j/neow3j#725]
With this SDK, how can I get the address from a raw 128-bit public key?

**Comment by csmuller** [comment]
You can use the constructor `io.neow3j.crypto.ECKeyPair.ECPublicKey(byte[] publicKey)` from the `core` module.
But your public key should be 33 bytes  in compressed form (from a minimum of 257 bit necessary to encode all information). You can currently only use keys from the  secp256r1 curve.

**Comment by gsmachado** [comment]
> You can use the constructor `io.neow3j.crypto.ECKeyPair.ECPublicKey(byte[] publicKey)` from the `core` module. But your public key should be 33 bytes in compressed form (from a minimum of 257 bit necessary to encode all information). You can currently only use keys from the secp256r1 curve.

@Yangxin-GG did this answer your question?

**Comment by mialbu** [comment]
I'll close this issue. @Yangxin-GG please reopen, if your question was not fully answered.
