### ISSUE TITLE
Support Storage Schema generation for Neo Debugger

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#733]
In its latest pre-release, the Neo Debugger supports a storage schema concept that should soon be included in a normal release of the debugger. 

Neow3j needs to be updated to produce the necessary debug information supporting this feature. The implementation probably needs annotations that allow the dev to annotated storage keys with the expected types stored at that key or prefix.

Usage of the preview can be found [here](https://github.com/ngdenterprise/neo-contrib-token/tree/storage-schema-preview).

**Comment by gsmachado** [comment]
Given that the hackathon is approaching, I think this has some prio.

What do you think, @csmuller @mialbu?

**Comment by gsmachado** [comment]
Oh, this is a non-breaking feature. 

In this case, the prio goes down a bit. Let me know your opinion.

**Comment by gsmachado** [comment]
Should we include it in https://github.com/neow3j/neow3j/milestone/20 ?

@mialbu

**Comment by csmuller** [comment]
Will be handled in #866.
