### ISSUE TITLE
Add single byte support for ContractParameter

### ISSUE THREAD

**Issue by ykoitzsch** [neow3j/neow3j#736]
**Summary or problem description**
I would like my public contract method to accept a byte as a parameter instead of a byteArray. My workaround for now is to accept byteArray and access the 0-index of it to get the byte I want.

**Do you have any solution you want to propose?**
If possible add support to the ContractParameter class to have a ContractParameter.byte() method.

**Comment by csmuller** [comment]
As a side note: A `byte` parameter in your contract method will be an integer stack item at runtime. I.e., you can use `ContractParameter.integer()` at the moment to invoke your method with a byte value. 
Nonetheless, it makes sense to add the `ContractParameter.byte()` method 👌
