### ISSUE TITLE
Enable multiple providers for account information (e.g. UTXOs)

### ISSUE THREAD

**Issue by nimmortal** [neow3j/neow3j#74]
Hello,

Thank you for amazing release, which allows to invoke contracts. However, I face an issue due to unspents. Before sending any asset I need to fetch unspents like this `acct.updateAssetBalances(neow3j);`. Unfortunately, this method use a node method which can be enabled only by plugin (https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getunspents.html). Currently I cannot fetch unspents on my neo-local blockchain and also in testnet. I suggest you a workaround how it is done in neon-js. They use neoscanner api for that purpose. Maybe it is possible to implement as second option too (https://neoscan-testnet.io/docs/index.html#api-v1-get-3)

This should not be a big issue, because json structure is the same.

Thanks.

**Comment by claudemiller** [comment]
Hey @nimmortal 

In neow3j we did not plan to rely on neoscan. And adding this option now is quite a big deal, and we hope that we can work this out with you in another way at the moment.
So, do you need exactly the private blockchain that you are running currently? If not, you could use the privatenet docker image from AxLabs which has the RpcSystemAssetTrackerPlugin installed.
The following commands will get it running.
```
docker pull axlabs/neo-privatenet
docker run --rm -d --name neo-privatenet -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp axlabs/neo-privatenet
```

There are also RPC nodes in the testnet that suppor the RpcSystemAssetTrackerPlugin. The one at  http://seed9.ngd.network:20332 is one example.

Does this help?

**Comment by nimmortal** [comment]
@claudemiller good point, I understand your thoughts about neoscan. It is quite annoying always  search healthy node with all required plugins, especially on testnet. Currently I created a workaround for this.

**Comment by gsmachado** [comment]
@claudemiller @nimmortal One thing we could think about is:
Maybe, in the future, we could add the ability to specify custom "providers" to fetch unspents, claimgas, etc etc.
However, this is not a priority at the moment.

**Comment by gsmachado** [comment]
This issue is open for such a long time, and there's no strong requirement to be implemented now -- especially with the development and rollout of Neo3 chain.

Thus, I'm closing this one. If someone would like to further discuss we can re-open it. 👍  💯
