### ISSUE TITLE
Update neow3j related content on the developer portal

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#746]
Refers to https://developers.neo.org/resources
- [x] The picture for Neo Playground is still the neow3j logo, but should be the playground logo.
- [x] In the SDK section, instead of neow3j, the title is Neo Playground appears, though it has to be neow3j!

**Comment by mialbu** [comment]
The changes have been updated in the following PR: https://github.com/neo-project/neo-dev-portal/pull/35

I'll close this issue once the PR has been merged.
