### ISSUE TITLE
Examples with Oracles

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#750]
It would be good to have an Oracle example, in the [neow3j-examples-java](https://github.com/neow3j/neow3j-examples-java), to cover the following:

1. Fetch NEO price from a public API (hardcoding API key due to the sake of simplicity)
2. Write a super simple API server to provide results and integrate that into a smart contract using the OracleContract.

**Comment by gsmachado** [comment]
This is the integration test that @csmuller wrote:

https://github.com/neow3j/neow3j/blob/1e783dce92c47c22157d3395c10a66007ffba7b4/core/src/test-integration/resources/OracleTestContract.java

**Comment by mialbu** [comment]
I've added a oracle examples in commit https://github.com/neow3j/neow3j-examples-java/commit/7b91ae1fe566dccb3c2ca5789e5f43895464165d.

**Comment by gsmachado** [comment]
awesome stuff! 🎉
