### ISSUE TITLE
Add `LedgerContract.getTransactionSigners(...)` to the devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#759]
Neo 3.2.1 adds a new method `getTransactionSigners` on the `LedgerContract`. Neow3j's devpack has to support that as well.

**Comment by mialbu** [comment]
Note, that the binary data was removed from the TransactionSigner object (see https://github.com/neo-project/neo/pull/2708).

**Comment by mialbu** [comment]
Has been included in PR #794.
