### ISSUE TITLE
Fail compilation when developer tries to concatenate string with other type

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#760]
An example of this problem is the following:
Developers often want to concatenate strings with integers to print an event, log, or exception message. But, the neow3j compiler does not support string concatenation with other types as Java does.

So either we add extra functionality such that the compiler supports such concatenations or we make it clear at compile-time that it is not supported by throwing a compiler exception.

**Comment by gsmachado** [comment]
oh, this is a good and interesting issue! It'd enhance developer experience, for sure.

IMHO, I think we should prioritize this one.

What's your opinion, @mialbu?

**Comment by mialbu** [comment]
I agree, I'll mark it todo.
