### ISSUE TITLE
Allow transmission of failing transactions in `TransactionBuilder`

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#767]
The `TransactionBuilder` always throws an exception when building a transaction that holds a script leading to a VM FAULT. This is due to the lines at https://github.com/neow3j/neow3j/blob/af237d1ac9d93b6e1611aa749a5e781e6280d1ac/core/src/main/java/io/neow3j/transaction/TransactionBuilder.java#L384-L387

Sometimes we want a transaction to be invoked even if neow3j knows that it will fail, e.g., for contract tests. Therefore, we need a method to disable the above exception. I propose something like the following:

```java
public void setTransmitOnVMFault() { 
    this.transmitOnFault = true;
}
```

And then an extra check before throwing the exception: 
```java
if (response.getResult().hasStateFault() && !transmitOnFault) {
```

This can be implemented as a non-breaking change.

**Comment by gsmachado** [comment]
This should be a global config for neow3j.
