### ISSUE TITLE
Upgrade Bouncycastle dependency

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#783]
Upgrade bouncycastle dependency on core module due to a vulnerability (see [here](https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-2841508)).

**Comment by gsmachado** [comment]
- [ ] Update version
- [ ] "Release" locally
- [ ] Test the crypto functions (signature, verify, etc)
- [ ] Test using a different environment than your development set-up (i.e., different than IntelliJ)
