### ISSUE TITLE
June Epic

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#795]
- [x] #778
- [x] #772
- [x] #796 
- [x] #797 
- [x] #786 
- [x] #689 
- [x] #807 

~#690~

**Comment by gsmachado** [comment]
@csmuller and @mialbu I think https://github.com/neow3j/neow3j/issues/781 should be tackled even before NeoFS API.

wdyt?

**Comment by mialbu** [comment]
@gsmachado We should plan #781 for July. I'm collecting a list of issues for July. Let's discuss this list next Monday.

**Comment by gsmachado** [comment]
Sure! Agree. 😄 👍
