### ISSUE TITLE
Better way to create Hash160 from script hash string

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#801]
Currently the dev has to do the following to create a `Hash160` from a big-endian script hash string.
```java
new Hash160(Helper.reverse(StringLiteralHelper.hexToBytes("0xfffdc93764dbaddd97c48f252a53ea4643faa3fd").toByteArray()))
```
Crazy, right?

It would be preferable to have the following.
```java
new Hash160("0xfffdc93764dbaddd97c48f252a53ea4643faa3fd")
```

The same should be supported for `Hash256` and `ECPoint`.

**Comment by cryptodogge** [comment]
https://github.com/neow3j/neow3j/blob/main/core/src/main/java/io/neow3j/types/Hash160.java#L65
Cannot work here?
