### ISSUE TITLE
Migrate integration tests to JUnit 5

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#822]
The new int-test module uses JUnit 4 as its test framework, but the `ModuleTest` test class is based on JUnit 5. Therefore, it is not executed when running the tests of the int-test module.

One solution would be to separate the tests in int-test into different source stets and configure them separately under different `testIntegration` Gradle tasks. Then we'd have to collect them in one main `testIntegration` task that dependsOn all of them.

The other solution is to update all integration tests to JUnit 5. That's what this issue wants.

**Comment by gsmachado** [comment]
Migration guide: https://www.baeldung.com/junit-5-migration
