### ISSUE TITLE
NeoFS API: Design library API on neow3j side

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#832]
Outcome:
- [x] new branch on neow3j repo
- [x] create a new module on neow3j code
- [x] code skeleton of how developers would use the module (e.g., methods signatures, classes, convenience methods, etc etc) -- the exercise here is to see HOW NEOW3J USERS WOULD USE NEOFS.

**Comment by mialbu** [comment]
Check the internal Notion page about neow3j's NeoFS architecture. Building the detailed API is tackled in other issues.
