### ISSUE TITLE
Allow manual specification of transaction inputs

### ISSUE THREAD

**Issue by claudemiller** [neow3j/neow3j#84]
As discussed in issue #72, developers need the possibility to add transaction inputs manually in managed transaction (e.g. AssetTransfer).

Currently, the API is there but the functionality is not yet implemented.

**Comment by claudemiller** [comment]
Available in neow3j version 2.2.0.

**Comment by nimmortal** [comment]
@claudemiller good work. I want to clarify one specific case.
If my input tx has GAS and NEO outputs can I create two outputs for that in your implementation?

**Comment by claudemiller** [comment]
> @claudemiller good work. I want to clarify one specific case.
> If my input tx has GAS and NEO outputs can I create two outputs for that in your implementation?

@nimmortal Hey, I reply late because I was traveling last week.
Yes you are correct. Every UTXO is unique, and so even if two UTXOs origin from the same transaction they have to be specified as two separate UTXOs.
Did you try it already?

**Comment by gsmachado** [comment]
@claudemiller maybe we could have an integration test with that, just to make sure... but let's take that on our TODOs.
