### ISSUE TITLE
NeoFS SDK: Create beta version implementation for objects

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#850]
This includes the following NeoFS methods:

- Create object (without session)
- Read object (without session)
- Delete object

Tasks:
- [x] createObject
- [x] readObject
- [x] deleteObject

**Comment by gsmachado** [comment]
Waiting for NSPCC for example.

**Comment by gsmachado** [comment]
An example was given!

Can we un-block this task? 😄

**Comment by mialbu** [comment]
Creating and reading an object works fine now.

However, deleting an object doesn't work yet. When calling `client.DeleteObjec()` in the shared-lib, the process runs seemingly forever.

**Comment by mialbu** [comment]
> However, deleting an object doesn't work yet. When calling `client.DeleteObjec()` in the shared-lib, the process runs seemingly forever.

I've fixed this. Deleting an object now works fine.
