### ISSUE TITLE
Add default CallFlags to contracts in devpack

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#857]
The contracts provided in neow3j's devpack should hold default `CallFlags`. Currently, when an existing method is used from a contract class in the devpack `CallFlags.All` is used for that contract call.

Check the required call flags for all native contract methods and add them with the annotation `@CallFlags` to all corresponding methods in the devpack. Additionally, add required call flags to the provided contract interface methods, such as NEP-17 methods.

In order to use custom call flags for a provided method, the developer can extend the class and override the method with the annotation `@Override` and the desired call flags with `@CallFlags`.

**Comment by Lorenzobattistela** [comment]
I'm up to pick up this one!
I'll investigate further and ask questions if needed.
Feel free to assign me as well

**Comment by mialbu** [comment]
@Lorenzobattistela
The value in the annotation has to be a byte value. You can use the constants of `io.neow3j.devpack.constants.CallFlags` for this.

**Comment by mialbu** [comment]
@Lorenzobattistela Also, I suggest you to read the code of the native contracts [here](https://github.com/neo-project/neo/tree/master/src/Neo/SmartContract/Native) and set the call flags in neow3j accordingly.

For example, the method `getMinimumDeploymentFee` of the native contract `ContractManagement` has call flags `ReadStates`:
https://github.com/neo-project/neo/blob/4a5a7f58567c1bf270d1c5515d90486c803b4e11/src/Neo/SmartContract/Native/ContractManagement.cs#L125-L129

**Comment by Lorenzobattistela** [comment]
Yes, this is exactly what I am doing haha, I was just a little confused about the callFlags import and syntax (rusty java here). But thanks, really helpful.

**Comment by mialbu** [comment]
Done in #1031
