### ISSUE TITLE
Documentation: Create contribution section

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#867]
Create documentation on how to setup up neow3j for contributing changes. This should include:
- What software to install (e.g., which Java version, recommended IDE)
- Checking out the repository
- Setting up auto-formatting that is included in the repo
- Run unit and integration tests
  - And thus, setting up the environment for running the integration tests

**Comment by gsmachado** [comment]
@csmuller it'd be nice if you could take this issue this (last) sprint.

**Comment by mialbu** [comment]
Has been done in #1078 (will be merged shortly).
