### ISSUE TITLE
NeoFS SDK: Convert neow3j NeoFS support architecture to figure

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#872]

**Comment by mialbu** [comment]
@gsmachado @csmuller Can you give some feedback on the following figure I've created?

![Image](https://user-images.githubusercontent.com/53603111/210216817-9fabc0d6-62dc-48c8-afbf-921ba55fbcc2.jpeg)

**Comment by mialbu** [comment]
![Image](https://user-images.githubusercontent.com/53603111/210236907-92c8bca4-572f-45de-a860-2a90f73c6326.jpeg)

**Comment by csmuller** [comment]
What does "Java-serialized" mean in this context? Maybe there's another word that is clearer?

**Comment by mialbu** [comment]
> What does "Java-serialized" mean in this context? Maybe there's another word that is clearer?

Is `Generated Java NeoFS API` more clear?

**Comment by csmuller** [comment]
Yes :)

**Comment by mialbu** [comment]
I've pushed the latest update in 86d645f.
