### ISSUE TITLE
sendtoaddress feature?

### ISSUE THREAD

**Issue by pavel-corsaghin** [neow3j/neow3j#9]
Hi, please add sendtoaddress feature. I can't find it in this project. Thank you :)

**Comment by gsmachado** [comment]
@pavel-corsaghin thanks for the feature request! Definitely, this would be implemented in the near future.

However, what are you trying to achieve?
If you simply want to send NEO assets from your address to another, and it does not matter where you hold your NEO assets, you can use the raw transaction feature in this project. :-)
If the wallet/address you want to send the assets from is located locked in a NEO node, then, you have two options: 1) either you export the wallet in the WIF format and import it using neow3j; or 2) you can unlock the NEO wallet on the NEO GUI and then use the upcoming `sendtoaddress` feature as you requested.

**Comment by pavel-corsaghin** [comment]
i am trying with this:
`val ecKeyPair = ECKeyPair.create(WIF.getPrivateKeyFromWIF("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))
        val neoAddress = Keys.getAddress(ecKeyPair)
        log("address: $neoAddress")

        val rawTx = RawTransaction.createContractTransaction(
            null, null,
            Arrays.asList(
                RawTransactionInput("9feac4774eb0f01ab5d6817c713144b7c020b98f257c30b1105062d434e6f254", 0)
            ),
            Arrays.asList(
                RawTransactionOutput(0, NEOAsset.HASH_ID, "100.0", "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y")
            )
        )
        val rawTxUnsignedArray = rawTx.toArray()
        val rawInvocationScriptList = Arrays.asList(RawInvocationScript(Sign.signMessage(rawTxUnsignedArray, ecKeyPair)))
        rawTx.addScript(rawInvocationScriptList, Keys.getVerificationScriptFromPublicKey(1, ecKeyPair.publicKey))
        val rawTxSignedArray = rawTx.toArray()
        val rawTransactionHexString = Numeric.toHexStringNoPrefix(rawTxSignedArray)
        log("rawTransactionHexString: $rawTransactionHexString" )`

But i am not sure about list RawTransactionInput. This is list UTXOs (history transactions of sender address)?. What prevHash and prevIndex means?

**Comment by gsmachado** [comment]
@pavel-corsaghin so, [release version 1.0.8](https://github.com/neow3j/neow3j/releases/tag/1.0.8) includes support to `sendtoaddress`. :-)

**Comment by gsmachado** [comment]
@pavel-corsaghin just replying to your last message: yes, the `RawTransactionInput` relates to the unspent amount that you're planning to spend. Then, the `prevHash` is the hash of the previous unspent transaction (output), and the `prevIndex` is the index of the previous transaction (also output).

**Comment by gsmachado** [comment]
For now, I'm going to close this issue. Let me know if you have some other issues.
By the way, you can always join NEO Discord and ask `neow3j` questions on the #java channel.
