### ISSUE TITLE
Update Neo v3.5.0 compatible `neo-express` version once released

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#903]

**Comment by gsmachado** [comment]
any news about this?

can you ping devhawk?

**Comment by mialbu** [comment]
No news yet, just pinged him. Waiting for an ETA for neo-express.

**Comment by gsmachado** [comment]
https://github.com/neo-project/neo-express/releases/tag/3.5.20

**Comment by mialbu** [comment]
Done (#907)
