### ISSUE TITLE
Add support for `System.Runtime.LoadScript` to devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#905]
In [this PR](https://github.com/neo-project/neo/pull/2756) (incl. in Neo 3.5.0) a new syscall `System.Runtime.LoadScript` was added that allows a smart contract to load and execute any VM script.

**Comment by gsmachado** [comment]
@mialbu @csmuller 
Can we think about a feature that uses the `System.Runtime.LoadScript` more fluidly in the devpack? I mean, e.g., as an annotation or smth like this?

Do you think this could be used somehow? Or is this a feature that would potentially have ZERO usage and doesn't worth our time to make it easier?

**Comment by mialbu** [comment]
> @mialbu @csmuller 
> 
> Can we think about a feature that uses the `System.Runtime.LoadScript` more fluidly in the devpack? I mean, e.g., as an annotation or smth like this?
> 
> 
> 
> Do you think this could be used somehow? Or is this a feature that would potentially have ZERO usage and doesn't worth our time to make it easier?

Imo, this syscall will only be used in more advanced cases. Devs can already use the syscall in an annotation with preceeding instruction annotations providing the script, callflags and arguments within (as long as they are constant). However, there's not really something we can improve easily and I don't think providing additional code (e.g., an interface for it) will justify the time we'll spend implementing it.
