### ISSUE TITLE
NeoFS SDK: aarch64 should be supported

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#911]
NeoFS Loader should support `aarch64` as architecture, analogous to `arm64`.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/2124276/211636618-72f0db71-6224-49bf-98b2-6c32c832ea1b.png">

More specifically, [this method](https://github.com/neow3j/neow3j/blob/253ce68b370903f99978c940178dc3c8d0612531/neofs/src/main/java/io/neow3j/neofs/lib/NeoFSLibUtils.java#L33) should be changed/adapted, maybe [in this line](https://github.com/neow3j/neow3j/blob/253ce68b370903f99978c940178dc3c8d0612531/neofs/src/main/java/io/neow3j/neofs/lib/NeoFSLibUtils.java#L35).

**Comment by mialbu** [comment]
This has been committed in 8b67d24. I'll close this. We can track this further in https://github.com/AxLabs/neofs-shared-lib/issues/13.
