### ISSUE TITLE
invocation_with_network_fee

### ISSUE THREAD

**Issue by yfhuang521** [neow3j/neow3j#92]
Can invocation_with_network_fee work properly?

**Comment by yfhuang521** [comment]
neow3j.wallet.exceptions.InsufficientFundsException: Account balance does not contain the asset with ID 602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7

But the account contain GAS

**Comment by yfhuang521** [comment]
![image](https://user-images.githubusercontent.com/21332031/63662604-9e655e80-c7f1-11e9-8883-4a9c3ac2ca7a.png)

hi @claudemiller

**Comment by gsmachado** [comment]
Hello @yfhuang521
Yes, this feature works and we have tests for it.

Can you please execute the following and paste here the result?

```
NeoGetBalance balance = neow3j.getBalance(GASAsset.HASH_ID).send();
System.out.println("Result: " + balance.getBalance());
```

**Comment by yfhuang521** [comment]
hi @gsmachado 
this is the result
--------------------------
Result: Balance{balance='0', confirmed='0'}
Result: State{version=0, id='0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7', type=UTILITY_TOKEN, names=[AssetName{lang='zh-CN', name='小蚁币'}, AssetName{lang='en', name='AntCoin'}], amount='100000000', available='0', precision=8, fee=null, address='null', owner='00', admin='AWKECj9RD8rS8RPcpCgYVjk1DeYyHwxZm3', issuer='AWKECj9RD8rS8RPcpCgYVjk1DeYyHwxZm3', expiration=4000000, frozen=false}
-------------------------

**Comment by gsmachado** [comment]
Hello @yfhuang521 
Your result "Result: Balance{balance='0', confirmed='0'}" shows that you don't have GAS in your wallet! That's why your invocation does not work properly.

**Comment by yfhuang521** [comment]
> Hello @yfhuang521
> Your result "Result: Balance{balance='0', confirmed='0'}" shows that you don't have GAS in your wallet! That's why your invocation does not work properly.

But actually my account have GAS.
see
https://user-images.githubusercontent.com/21332031/63736087-8276c100-c8b4-11e9-93a1-7e25a40beeed.png

**Comment by gsmachado** [comment]
@yfhuang521 
Are you using privatenet? Can you reproduce that using the privnet in docker, for example?
https://hub.docker.com/r/cityofzion/neo-privatenet

**Comment by yfhuang521** [comment]
@gsmachado 

![image](https://user-images.githubusercontent.com/21332031/63753411-9c7cc780-c8e5-11e9-9cc8-c8206fe94bba.png)


this is my code, and my account 'AVSURyYM58Mp8ULYLjXyZqcnpzTAUk9HoU' have NEO mainnet GAS,but the result is:
"neow3j.wallet.exceptions.InsufficientFundsException: Account balance does not contain the asset with ID 602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7"

is the 'https://node2.neocompiler.io' URL wrong?

**Comment by yfhuang521** [comment]
@gsmachado 
and i find the neo node method 'getunspents' doesn't work anymore.
![image](https://user-images.githubusercontent.com/21332031/63753632-01d0b880-c8e6-11e9-8e6c-722f36ba4496.png)
Does this method work on the bottom floor of the neow3j?

**Comment by yfhuang521** [comment]
@gsmachado 
it`s work, Use this node 'http://seed9.ngd.network:10332'
