### ISSUE TITLE
ZKP: Define test cases

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#920]
Ask the Neo team for test case scenarios.

Otherwise, come up with our own.

👉 talk to people and ask for references.

**Comment by mialbu** [comment]
@gsmachado
After adding and testing the bls12381 curve methods of the native CryptoLib in the devpack, I don't think that we'll need special methods for it in the SDK. I think these methods should be used and called within another smart contract.

I'll close this issue.
