### ISSUE TITLE
Add utility methods to get first items

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#924]
**Summary or problem description**
Neow3j has many methods to return a list of objects where the first item is important. This results in many lines of code that contain `.get(0)`.

**Do you have any solution you want to propose?**
In order to simplify this, neow3j could add two kind of methods:
- A method that accesses the first index, e.g., `.getFirstStackItem()`
- A method that takes an index as a parameter to directly retrieve the item without having to call `.get(i)`. This would make the code appear more succinct. For example: `.getStackItem(2)`, instead of `getStack().get(2)`

**What part of neow3j does this apply to?**
- SDK

**Comment by gsmachado** [comment]
I'm in favor. This is just additions to the convenience layer, and not drastic changes. 👍
