### ISSUE TITLE
Create list of all supported packages, classes and methods

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#926]
### Create a list of all supported
- [ ] packages
- [ ] classes
- [ ] methods
- [ ] static variables

This might involve annotations for custom created classes/methods/variables

**Comment by csmuller** [comment]
I'm not fully understanding what you mean @gsmachado.
Sounds like javadoc to me.

**Comment by gsmachado** [comment]
> I'm not fully understanding what you mean @gsmachado. Sounds like javadoc to me.

hmmm, I thought about having a list of methods/types.

But, thinking a bit better, I agree: this would be the same as a JavaDoc. 👍 

What about if we change this issue a bit and create docs for neow3j types and a description of the limitation of java built-in functions? Do you think this would be helpful?

cc @csmuller @mialbu

**Comment by gsmachado** [comment]
After the daily, I realized that this issue should be closed and not further action should be done.
