### ISSUE TITLE
Remove multiple JsonValue annotations in enums

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#947]
With never jackson versions, multiple `JsonValue` annotations in an enum (e.g., `NeoVMStateType`) seem to run into problems when deserializing. These should be removed.

**Comment by gsmachado** [comment]
Can we have a unit test that would test if these changes ever again?

I mean: why didn't we realize this problem with our unit tests?

**Comment by csmuller** [comment]
@gsmachado Since the problem only arose due to a different Jackson version of the user, there was no way of testing this with a simple unit test.
