### ISSUE TITLE
Upgrade Gradle Version

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#948]

**Comment by gsmachado** [comment]
We should:
- upgrade gradle version of the whole neow3j project
- upgrade gradle version of the gradle-plugin

these are two different things, but I believe it can be tackled in the same issue.

**Comment by gsmachado** [comment]
Some pending TODOs:

- [ ] Change `GRADLE_MIN_VERSION` variable on `Neow3jPlugin.class` (and test this!)
- [ ] Adapt `ci-cd.yml` for GitHub Actions (we need a newer Java version if we want to keep `org.unbroken-dome.test-sets` plugin -- it can't run with Java 1.8 anymore)
- [ ] Maybe we should remove `org.unbroken-dome.test-sets` for good and forever. It seems that the [Test Suite feature](https://docs.gradle.org/8.2/userguide/jvm_test_suite_plugin.html) of newer Gradle versions already support everything we're using from `org.unbroken-dome.test-sets` plugin. 😉 
- [ ] Manual testing (with a real project + SNAPSHOT)
