### ISSUE TITLE
sendrawtransaction  failed

### ISSUE THREAD

**Issue by swq123** [neow3j/neow3j#95]
{
    "attributes": [
        
    ],
    "contractScript": "CjA1NDMzNTM5NjYiQWFwbnE5cW1vWTRqVFQyUmlHQTVzQ3RMN1doQUNGUnlzSFLBBnNpZ25JbmeofHl2Zi+bIBLCpazmoNvW9TLSWQ==",
    "inputs": [
        
    ],
    "outputs": [
        
    ],
    "scripts": [
        {
            "invocationScript": {
                "script": "QMm4sKTZ9N6IaPaJmI5hjGEy4PEfZejwbX3b+tCAvxuuOdb9+6Xe2UjNxOVfFl8dGND3IjL05GQN8eamwmR5xCw="
            },
            "scriptHash": "0PeeCctzgK3EtYcMrian++LQgzo=",
            "verificationScript": {
                "script": "IQI4lZ09NJrVkaSxAIu9NDHYACYVDFMH7ARNCphn+TSyE6w=",
                "scriptHash": "0PeeCctzgK3EtYcMrian++LQgzo=",
                "signingThreshold": 1
            }
        }
    ],
    "transactionType": "INVOCATION_TRANSACTION",
    "txId": "5c08c5db0f1b55313c42138be34e22bae71e2dadd416605bc3140bd8384d336b",
    "version": 1
}

rawHex：d1014c0a30353433333533393636224161706e7139716d6f59346a54543252694741357343744c3757684143465279734852c1067369676e496e67a87c7976662f9b2012c2a5ace6a0dbd6f532d2590000000000000000000000014140c9b8b0a4d9f4de8868f689988e618c6132e0f11f65e8f06d7ddbfad080bf1bae39d6fdfba5ded948cdc4e55f165f1d18d0f72232f4e4640df1e6a6c26479c42c23210238959d3d349ad591a4b1008bbd3431d80026150c5307ec044d0a9867f934b213ac

method：sendrawtransaction

error:

{"id":1,"jsonrpc":"2.0","error":{"code":-504,"message":"Block or transaction validation failed."}}

**Comment by gsmachado** [comment]
Hello @swq123 
Can you please paste here how you created the transaction (the code), please?

**Comment by swq123** [comment]
This problem has been solved, thank you

**Comment by gsmachado** [comment]
Thanks for reporting, @swq123!
