### ISSUE TITLE
Evaluate: How easy is it to update neo-express to a new Neo version?

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#958]
Maybe the neo core is only a dependency of neo-express 🙏

**Comment by gsmachado** [comment]
@mialbu you should evaluate the new version: https://www.nuget.org/packages/Neo.Express

**Comment by mialbu** [comment]
Imo, we can close this issue as there is more wide-spread interest on neo-express and it'll be looked after (even though the maintenance task is not yet assigned).
