### ISSUE TITLE
Evaluate: Can we use neo-go as a replacement of neo-express in devpack-test?

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#959]
- [ ] Define the necessary features (check the `TestBlockchain` interface in neow3j)
- [ ] Ask NSPCC if their node supports these features

**Comment by mialbu** [comment]
Should we even keep this issue open, @csmuller @gsmachado? Imo, we could close it.

**Comment by gsmachado** [comment]
We can close for now. If it becomes relevant, then we can open it again.
