### ISSUE TITLE
There is a problem with the change processing logic

### ISSUE THREAD

**Issue by Java1024** [neow3j/neow3j#98]
private void calculateInputsAndChange(Map<String, BigDecimal> requiredAssets, Account 
 changeAcct) {

            requiredAssets.forEach((assetId, requiredAmount) -> {
                List<Utxo> selectedUtxos = this.inputCalculationStrategy.calculateInputs(
                        this.utxos.get(assetId), requiredAmount);

                this.inputs.addAll(selectedUtxos.stream()
                        .map(Utxo::toTransactionInput)
                        .collect(Collectors.toList()));

                this.outputs.add(getChangeTransactionOutput(assetId, requiredAmount,
                        selectedUtxos, changeAcct.getAddress()));
            });
        }

        private RawTransactionOutput getChangeTransactionOutput(String assetId,
                                                                BigDecimal requiredValue,
                                                                List<Utxo> utxos,
                                                                String changeAddress) {

            BigDecimal inputAmount = utxos.stream().map(Utxo::getValue).reduce(BigDecimal::add).get();
            if (inputAmount.compareTo(requiredValue) <= 0) {
                return null;
            }
            BigDecimal change = inputAmount.subtract(requiredValue);
            return new RawTransactionOutput(assetId, change.toPlainString(), changeAddress);
        }

Output will add a null if all assets are not removed, causing a java.lang.NullPointerException to occur with writeSerializableFixed()

**Comment by gsmachado** [comment]
@Java1024 thanks for your report! We'll definitely look into it.
Can you please provide us a reproduction case?

**Comment by Java1024** [comment]
Neow3j neow3j = Neow3j.build(new HttpService("http://seed7.ngd.network:10332"));
Account multiSigAcct = Account.fromAddress("ATcWffQV1A7NMEsqQ1RmKfS7AbSqcAp2hd").build();
multiSigAcct.updateAssetBalances(neow3j);
AssetTransfer at = new AssetTransfer.Builder(neow3j)
        .account(multiSigAcct)
        .output(NEOAsset.HASH_ID, 1, "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y")
        .build();

byte[] unsignedTxHex = at.getTransaction().toArrayWithoutScripts();
SignatureData sig1 = Sign.signMessage(unsignedTxHex, keyPair1);
SignatureData sig2 = Sign.signMessage(unsignedTxHex, keyPair2);
RawScript witness = RawScript.createMultiSigWitness(2, Arrays.asList(sig1, sig2), keys);
at.addWitness(witness).send();  

As with the documentation, executing byte[] unsignedTxHex = at.getTransaction().toArrayWithoutScripts(); will report java.lang.NullPointerException

**Comment by csmuller** [comment]
Fixed the issue. Though, release date of next neow3j patch version is not set yet.

**Comment by gsmachado** [comment]
Released on [2.3.1](https://github.com/neow3j/neow3j/releases/tag/2.3.1).
